class CameraUiCopy {
  const CameraUiCopy._();

  static String t(String languageCode, String key) {
    final code = languageCode.toLowerCase().split('-').first;
    return (_copy[code] ?? _copy['en']!)[key] ?? _copy['en']![key] ?? key;
  }

  static const Map<String, Map<String, String>> _copy = {
    'it': {
      'initializing': 'INIZIALIZZAZIONE...',
      'noCamera': 'FOTOCAMERA NON DISPONIBILE',
      'ready': 'PRONTO',
      'error': 'ERRORE',
      'zoomError': 'ERRORE ZOOM',
      'physicalProbe': 'CONTROLLO AUTOMATICO DELLA SCENA...',
      'starting': 'AVVIO REGISTRAZIONE...',
      'recording': 'REGISTRAZIONE IN CORSO...',
      'startError': 'ERRORE AVVIO',
      'processingVideo': 'ELABORAZIONE VIDEO...',
      'stopError': 'ERRORE ARRESTO',
      'takingPhoto': 'SCATTO FOTO...',
      'analyzingScreen': 'ANALISI DEL RISCHIO RIPRESA DA SCHERMO...',
      'addingWatermark': 'AGGIUNTA WATERMARK SIGILLUM...',
      'addingLogo': 'AGGIUNTA SIGILLUM...',
      'creatingCertificate': 'CREAZIONE CERTIFICATO HCV...',
      'savingVideo': 'SALVATAGGIO VIDEO...',
      'watermarkError': 'ERRORE WATERMARK',
      'renameError': 'ERRORE RINOMINA',
      'photoVerified': 'FOTO VERIFICATA',
      'photoInvalid': 'FOTO NON VALIDA',
      'photoError': 'ERRORE FOTO',
      'done': 'COMPLETATO',
      'humanVerified': 'CERTIFICAZIONE COMPLETATA',
      'notVerified': 'NON VERIFICATO',
      'registryPublishing': 'Registrazione certificato nel Registry...',
      'registryOk': 'Registry OK',
      'certificatePublished': 'certificato registrato',
      'registryPending':
          'Certificato salvato: registrazione Registry in attesa',
      'registryUnavailableLocal':
          'Certificato salvato localmente. Registry non raggiungibile',
      'registrySubscriptionRequired':
          'CERTIFICATO SALVATO — ABBONAMENTO CREATOR NON ATTIVO. RIATTIVA L’ABBONAMENTO PER REGISTRARLO NEL REGISTRY.',
      'registryCreatorSessionRequired':
          'CERTIFICATO SALVATO — SESSIONE CREATOR SCADUTA. ACCEDI DI NUOVO PER REGISTRARLO NEL REGISTRY.',
      'registrySynced': 'Registry sincronizzato',
      'registryPublished': 'registrati',
      'registryWaiting': 'in attesa',
      'hcvCopied': 'HCV-ID copiato',
      'noFileToShare': 'NESSUN FILE DA CONDIVIDERE',
      'verifiedContent': 'Contenuto verificato SIGILLUM',
      'shareError': 'ERRORE CONDIVISIONE',
      'savedToPhotos': 'Salvato anche in Foto',
      'photosPermissionUnavailable':
          'Non salvato in Foto: permesso non disponibile',
      'noPackToShare': 'NESSUN PACCHETTO DA CONDIVIDERE',
      'sharePackError': 'ERRORE CONDIVISIONE HCVPACK',
      'photoLower': 'foto',
      'videoLower': 'video',
      'contentLower': 'contenuto',
      'photoTitle': 'Foto',
      'videoTitle': 'Video',
      'contentTitle': 'Contenuto',
      'verifiableCreated': 'verificabile creato',
      'linkedFiles':
          'sono collegati dallo stesso HCV-ID. La verifica online usa HCV-ID e Registry.',
      'copyHcvId': 'COPIA HCV-ID',
    },
    'en': {
      'initializing': 'INITIALIZING...',
      'noCamera': 'CAMERA NOT AVAILABLE',
      'ready': 'READY',
      'error': 'ERROR',
      'zoomError': 'ZOOM ERROR',
      'physicalProbe': 'AUTOMATIC SCENE CHECK...',
      'starting': 'STARTING RECORDING...',
      'recording': 'RECORDING...',
      'startError': 'START ERROR',
      'processingVideo': 'PROCESSING VIDEO...',
      'stopError': 'STOP ERROR',
      'takingPhoto': 'TAKING PHOTO...',
      'analyzingScreen': 'ANALYZING SCREEN-RECAPTURE RISK...',
      'addingWatermark': 'ADDING SIGILLUM WATERMARK...',
      'addingLogo': 'ADDING SIGILLUM...',
      'creatingCertificate': 'CREATING HCV CERTIFICATE...',
      'savingVideo': 'SAVING VIDEO...',
      'watermarkError': 'WATERMARK ERROR',
      'renameError': 'RENAME ERROR',
      'photoVerified': 'PHOTO VERIFIED',
      'photoInvalid': 'PHOTO INVALID',
      'photoError': 'PHOTO ERROR',
      'done': 'DONE',
      'humanVerified': 'CERTIFICATION COMPLETE',
      'notVerified': 'NOT VERIFIED',
      'registryPublishing': 'Registering certificate in the Registry...',
      'registryOk': 'Registry OK',
      'certificatePublished': 'certificate registered',
      'registryPending': 'Certificate saved: Registry registration pending',
      'registryUnavailableLocal':
          'Certificate saved locally. Registry unavailable',
      'registrySubscriptionRequired':
          'CERTIFICATE SAVED — CREATOR SUBSCRIPTION NOT ACTIVE. REACTIVATE IT TO REGISTER IT IN THE REGISTRY.',
      'registryCreatorSessionRequired':
          'CERTIFICATE SAVED — CREATOR SESSION EXPIRED. SIGN IN AGAIN TO REGISTER IT IN THE REGISTRY.',
      'registrySynced': 'Registry synchronized',
      'registryPublished': 'registered',
      'registryWaiting': 'pending',
      'hcvCopied': 'HCV-ID copied',
      'noFileToShare': 'NO FILE TO SHARE',
      'verifiedContent': 'SIGILLUM verified content',
      'shareError': 'SHARE ERROR',
      'savedToPhotos': 'Also saved to Photos',
      'photosPermissionUnavailable':
          'Not saved to Photos: permission unavailable',
      'noPackToShare': 'NO PACKAGE TO SHARE',
      'sharePackError': 'HCVPACK SHARE ERROR',
      'photoLower': 'photo',
      'videoLower': 'video',
      'contentLower': 'content',
      'photoTitle': 'Photo',
      'videoTitle': 'Video',
      'contentTitle': 'Content',
      'verifiableCreated': 'verifiable file created',
      'linkedFiles':
          'are linked by the same HCV-ID. Online verification uses the HCV-ID and Registry.',
      'copyHcvId': 'COPY HCV-ID',
    },
    'es': {
      'initializing': 'INICIALIZANDO...',
      'noCamera': 'CÁMARA NO DISPONIBLE',
      'ready': 'LISTO',
      'error': 'ERROR',
      'zoomError': 'ERROR DE ZOOM',
      'physicalProbe': 'COMPROBACIÓN AUTOMÁTICA DE LA ESCENA...',
      'starting': 'INICIANDO GRABACIÓN...',
      'recording': 'GRABANDO...',
      'startError': 'ERROR DE INICIO',
      'processingVideo': 'PROCESANDO VIDEO...',
      'stopError': 'ERROR AL DETENER',
      'takingPhoto': 'TOMANDO FOTO...',
      'analyzingScreen': 'ANALIZANDO RIESGO DE RECAPTURA DE PANTALLA...',
      'addingWatermark': 'AÑADIENDO WATERMARK SIGILLUM...',
      'addingLogo': 'AÑADIENDO SIGILLUM...',
      'creatingCertificate': 'CREANDO CERTIFICADO HCV...',
      'savingVideo': 'GUARDANDO VIDEO...',
      'watermarkError': 'ERROR DE WATERMARK',
      'renameError': 'ERROR AL RENOMBRAR',
      'photoVerified': 'FOTO VERIFICADA',
      'photoInvalid': 'FOTO NO VÁLIDA',
      'photoError': 'ERROR DE FOTO',
      'done': 'COMPLETADO',
      'humanVerified': 'CERTIFICACIÓN COMPLETADA',
      'notVerified': 'NO VERIFICADO',
      'registryPublishing': 'Registrando el certificado en el Registry...',
      'registryOk': 'Registry OK',
      'certificatePublished': 'certificado registrado',
      'registryPending':
          'Certificado guardado: registro en el Registry pendiente',
      'registryUnavailableLocal':
          'Certificado guardado localmente. Registry no disponible',
      'registrySubscriptionRequired':
          'CERTIFICADO GUARDADO — SUSCRIPCIÓN CREATOR NO ACTIVA. REACTÍVALA PARA REGISTRARLO EN EL REGISTRY.',
      'registryCreatorSessionRequired':
          'CERTIFICADO GUARDADO — SESIÓN CREATOR CADUCADA. INICIA SESIÓN DE NUEVO PARA REGISTRARLO EN EL REGISTRY.',
      'registrySynced': 'Registry sincronizado',
      'registryPublished': 'registrados',
      'registryWaiting': 'pendientes',
      'hcvCopied': 'HCV-ID copiado',
      'noFileToShare': 'NINGÚN ARCHIVO PARA COMPARTIR',
      'verifiedContent': 'Contenido verificado por SIGILLUM',
      'shareError': 'ERROR AL COMPARTIR',
      'savedToPhotos': 'También guardado en Fotos',
      'photosPermissionUnavailable':
          'No guardado en Fotos: permiso no disponible',
      'noPackToShare': 'NINGÚN PAQUETE PARA COMPARTIR',
      'sharePackError': 'ERROR AL COMPARTIR HCVPACK',
      'photoLower': 'foto',
      'videoLower': 'video',
      'contentLower': 'contenido',
      'photoTitle': 'Foto',
      'videoTitle': 'Video',
      'contentTitle': 'Contenido',
      'verifiableCreated': 'verificable creado',
      'linkedFiles':
          'están vinculados por el mismo HCV-ID. La verificación online usa el HCV-ID y el Registry.',
      'copyHcvId': 'COPIAR HCV-ID',
    },
    'ru': {
      'initializing': 'ИНИЦИАЛИЗАЦИЯ...',
      'noCamera': 'КАМЕРА НЕДОСТУПНА',
      'ready': 'ГОТОВО',
      'error': 'ОШИБКА',
      'zoomError': 'ОШИБКА МАСШТАБА',
      'physicalProbe': 'АВТОМАТИЧЕСКАЯ ПРОВЕРКА СЦЕНЫ...',
      'starting': 'ЗАПУСК ЗАПИСИ...',
      'recording': 'ИДЁТ ЗАПИСЬ...',
      'startError': 'ОШИБКА ЗАПУСКА',
      'processingVideo': 'ОБРАБОТКА ВИДЕО...',
      'stopError': 'ОШИБКА ОСТАНОВКИ',
      'takingPhoto': 'СЪЁМКА ФОТО...',
      'analyzingScreen': 'АНАЛИЗ РИСКА ПЕРЕСЪЁМКИ ЭКРАНА...',
      'addingWatermark': 'ДОБАВЛЕНИЕ WATERMARK SIGILLUM...',
      'addingLogo': 'ДОБАВЛЕНИЕ SIGILLUM...',
      'creatingCertificate': 'СОЗДАНИЕ HCV-СЕРТИФИКАТА...',
      'savingVideo': 'СОХРАНЕНИЕ ВИДЕО...',
      'watermarkError': 'ОШИБКА WATERMARK',
      'renameError': 'ОШИБКА ПЕРЕИМЕНОВАНИЯ',
      'photoVerified': 'ФОТО ПРОВЕРЕНО',
      'photoInvalid': 'ФОТО НЕДЕЙСТВИТЕЛЬНО',
      'photoError': 'ОШИБКА ФОТО',
      'done': 'ЗАВЕРШЕНО',
      'humanVerified': 'СЕРТИФИКАЦИЯ ЗАВЕРШЕНА',
      'notVerified': 'НЕ ПРОВЕРЕНО',
      'registryPublishing': 'Регистрация сертификата в Registry...',
      'registryOk': 'Registry OK',
      'certificatePublished': 'сертификат зарегистрирован',
      'registryPending': 'Сертификат сохранён: регистрация в Registry ожидается',
      'registryUnavailableLocal':
          'Сертификат сохранён локально. Registry недоступен',
      'registrySubscriptionRequired':
          'СЕРТИФИКАТ СОХРАНЁН — ПОДПИСКА CREATOR НЕ АКТИВНА. ВОЗОБНОВИТЕ ЕЁ ДЛЯ РЕГИСТРАЦИИ В REGISTRY.',
      'registryCreatorSessionRequired':
          'СЕРТИФИКАТ СОХРАНЁН — СЕССИЯ CREATOR ИСТЕКЛА. ВОЙДИТЕ СНОВА ДЛЯ РЕГИСТРАЦИИ В REGISTRY.',
      'registrySynced': 'Registry синхронизирован',
      'registryPublished': 'зарегистрировано',
      'registryWaiting': 'ожидает',
      'hcvCopied': 'HCV-ID скопирован',
      'noFileToShare': 'НЕТ ФАЙЛА ДЛЯ ОТПРАВКИ',
      'verifiedContent': 'Контент проверен SIGILLUM',
      'shareError': 'ОШИБКА ОТПРАВКИ',
      'savedToPhotos': 'Также сохранено в Фото',
      'photosPermissionUnavailable': 'Не сохранено в Фото: нет разрешения',
      'noPackToShare': 'НЕТ ПАКЕТА ДЛЯ ОТПРАВКИ',
      'sharePackError': 'ОШИБКА ОТПРАВКИ HCVPACK',
      'photoLower': 'фото',
      'videoLower': 'видео',
      'contentLower': 'контент',
      'photoTitle': 'Фото',
      'videoTitle': 'Видео',
      'contentTitle': 'Контент',
      'verifiableCreated': 'создан проверяемый файл',
      'linkedFiles':
          'связаны одним HCV-ID. Онлайн-проверка использует HCV-ID и Registry.',
      'copyHcvId': 'КОПИРОВАТЬ HCV-ID',
    },
  };
}
