import 'dart:ui';

class SigillumLanguage {
  const SigillumLanguage({
    required this.code,
    required this.name,
    required this.shortName,
  });

  final String code;
  final String name;
  final String shortName;
}

class SigillumCopy {
  static const languages = [
    SigillumLanguage(code: 'it', name: 'Italiano', shortName: 'IT'),
    SigillumLanguage(code: 'en', name: 'English', shortName: 'EN'),
    SigillumLanguage(code: 'es', name: 'Español', shortName: 'ES'),
    SigillumLanguage(code: 'ru', name: 'Русский', shortName: 'RU'),
  ];

  static String initialLanguageCode() {
    final localeCode = PlatformDispatcher.instance.locale.languageCode;
    return languages.any((language) => language.code == localeCode)
        ? localeCode
        : 'en';
  }

  static SigillumLanguage language(String code) {
    return languages.firstWhere(
      (language) => language.code == code,
      orElse: () => languages[1],
    );
  }

  static String t(String code, String key) {
    return (_copy[code] ?? _copy['en']!)[key] ?? _copy['en']![key] ?? key;
  }

  static const _copy = {
    'it': {
      'identity': 'Identità',
      'accountTitle': 'ACCOUNT',
      'accountSubtitle': 'Profilo, identità, KYC, sicurezza e dati.',
      'headline': 'Prova tecnica per contenuti creati da persone reali.',
      'subtitle':
          'SIGILLUM collega foto, video e testi a HCV-ID, identità tecnica, impronta crittografica del file, certificato firmato e Registry online. Per le copie ricompresse usa fingerprint percettivi specifici per il tipo di media.',
      'certifyMediaTitle': 'Crea e Certifica foto o video',
      'certifyMediaSubtitle': 'Scatta o registra e crea il certificato HCV.',
      'certifyTextTitle': 'Crea e Certifica testo',
      'certifyTextSubtitle': 'Crea un testo verificabile con HCV-ID.',
      'verifyTitle': 'Verifica contenuto',
      'verifySubtitle': 'Apri file, HCVPACK o verifica dal Registry.',
      'infoTitle': 'Informazioni e privacy',
      'infoSubtitle': 'Controlli, limiti, termini e supporto.',
      'quickGuideTitle': 'Come si usa SIGILLUM',
      'quickGuideSubtitle':
          'Guida rapida: camera, coordinate, flash, zoom, verifica e sottotitoli',
      'quickGuideTooltip': 'Come si usa',
      'trustChain': 'Catena di controllo',
      'controls': 'Controlli SIGILLUM',
      'capture': 'Cattura',
      'captureText': 'creata nell app',
      'fingerprint': 'Impronta',
      'fingerprintText': 'hash del file',
      'identityStep': 'Identità',
      'identityText': 'creatore collegato',
      'signature': 'Firma',
      'signatureText': 'certificato protetto',
      'registry': 'Registry',
      'registryText': 'verifica online',
      'checkIntegrity': 'Integrità del file e coerenza con il certificato',
      'checkSignature': 'Firma digitale del certificato',
      'checkWatermark': 'Watermark visibile nel contenuto pubblicato',
      'checkRegistry': 'Registry online per verifica futura',
      'checkScreen': 'Controllo rischio ripresa da schermo',
      'checkSocial': 'Compatibilità di copie ricompresse: fingerprint immagine per foto; fingerprint visivo e audio per video',
      'socialVerifyTitle': 'Verifica da social',
      'socialVerifyStep1':
          'Quando vedi un contenuto su Facebook, WhatsApp, Messenger o altri social, apri Condividi.',
      'socialVerifyStep2': 'Scegli SIGILLUM tra le app disponibili.',
      'socialVerifyStep3':
          'SIGILLUM usa HCV-ID o watermark visibile per identificare il certificato nel Registry; per una copia ricompressa verifica poi i fingerprint previsti per quel tipo di media.',
      'socialVerifyStep4':
          'Se il contenuto è certificato, vedi provenienza, integrità e identità tecnica; nei video moderni la compatibilità visiva e audio viene controllata separatamente.',
      'legalPageTitle': 'Informazioni',
      'legalIntro':
          'SIGILLUM crea una prova tecnica verificabile che collega contenuto, HCV-ID, identità tecnica del creatore, impronta crittografica del file e Registry online.',
      'legalControls': 'Controlli eseguiti',
      'legalData': 'Dati trattati',
      'legalLimits': 'Limiti del servizio',
      'data1': 'contenuto creato o selezionato dall utente',
      'data2': 'HCV-ID e impronta crittografica del file',
      'data3': 'metadati tecnici necessari alla verifica',
      'data4': 'identità tecnica del creatore, se configurata',
      'limit1':
          'SIGILLUM verifica provenienza tecnica e integrita, non sostituisce una perizia legale.',
      'limit2':
          'Un avviso di rischio schermo indica cautela, non prova automatica di falso.',
      'limit3':
          'La verifica online richiede che il Registry sia raggiungibile.',
      'privacyPolicy': 'Privacy policy',
      'terms': 'Termini del servizio',
      'support': 'Supporto e cancellazione dati',
      'deleteData': 'Cancellazione dati',
      'copied': 'Copiato',
      'technicalIdentityTitle': 'Identità tecnica',
      'technicalIdentityHeading': 'Identità tecnica SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM collega il contenuto a una chiave tecnica del dispositivo, a un nome dichiarato e, se completata, a una verifica documentale KYC.',
      'declaredName': 'Nome dichiarato',
      'saveName': 'SALVA NOME',
      'loadingTechnicalIdentity': 'Caricamento identità tecnica...',
      'technicalIdentityLoaded': 'Identità tecnica caricata',
      'enterDeclaredName': 'Inserisci il nome dichiarato',
      'declaredNameSaved': 'Nome dichiarato salvato',
      'technicalCreatorId': 'ID tecnico creator',
      'deviceKeyFingerprint': 'Impronta chiave dispositivo',
      'technicalIdentityFingerprint': 'Impronta identità tecnica',
      'identityAssurance': 'Garanzia identità',
      'legalIdentity': 'Identità legale',
      'verifiedLegalName': 'Nome legale verificato',
      'verifiedLegalCountry': 'Paese documento',
      'startKyc': 'Avvia verifica identità',
      'kycExplanation':
          'La verifica documentale KYC sara gestita da un provider esterno. SIGILLUM salvera solo lo stato minimo della verifica.',
      'kycStarting': 'Avvio verifica identita...',
      'kycLinkReady': 'Link KYC pronto. Aprilo nel browser:',
      'kycConfiguredNoUrl':
          'KYC configurato, ma il server non ha restituito un link.',
      'kycNotAvailable': 'KYC non ancora disponibile',
      'kycOpening': 'Apro la verifica identità...',
      'refreshKyc': 'Aggiorna stato verifica',
      'kycRefreshing': 'Aggiornamento stato verifica...',
      'kycNoSession': 'Nessuna sessione KYC avviata.',
      'kycVerified': 'Identità legale verificata.',
      'kycStatus': 'Stato KYC',
      'kycStatusLabel': 'Stato KYC',
      'kycStatusUnavailable': 'Stato KYC non disponibile',
      'kycRequiresInputHint':
          'Verifica incompleta: premi Avvia verifica identita per riprendere la stessa sessione Stripe.',
      'privacy': 'Privacy',
      'technicalProof': 'Prova tecnica',
      'notGeneratedYet': 'Non ancora generato',
      'verifyContentHeading': 'Verifica contenuto',
      'supportedFiles': 'Supportati:\n.hcvpack, .hcv, foto, video, testo, PDF',
      'selectFile': 'SELEZIONA FILE',
      'selectFileToVerify': 'Seleziona un file da verificare',
      'noFileSelected': 'Nessun file selezionato',
      'filePathUnavailable': 'Path file non disponibile',
      'fileSelected': 'File selezionato',
      'importError': 'Errore import',
      'analyzingFile': 'Analisi file...',
      'fileNotFound': 'File non trovato',
      'unknownFormat': 'Formato non riconosciuto',
      'selectHcv': 'SELEZIONA HCV',
      'selectOriginalMedia': 'SELEZIONA MEDIA ORIGINALE',
      'verifyFromRegistry': 'VERIFICA DA REGISTRY',
      'verifyingShort': 'VERIFICA...',
      'selectHcvFile': 'Seleziona file HCV',
      'selectHcvExtension': 'Seleziona un file .hcv',
      'selectHcvFirst': 'Seleziona prima un file HCV',
      'verifying': 'Verifica in corso...',
      'certificateValid': 'Certificato valido',
      'certificateInvalid': 'Certificato non valido',
      'issuer': 'Emittente',
      'hcvpackDetails': 'Dettagli verifica HCVPACK',
      'hcvpackSelect': 'Seleziona file .hcvpack',
      'hcvpackInvalid': 'Certificato HCV non valido',
      'hcvpackIncomplete': 'Certificato HCV incompleto',
      'verificationComplete': 'Verifica completata',
      'identityUnavailable': 'Identità non disponibile',
      'fileType': 'Tipo file',
      'trustLevel': 'Livello fiducia',
      'liveCapture': 'Cattura live',
      'screenReplayRisk': 'Rischio ripresa schermo',
      'syntheticRisk': 'Rischio sintetico',
      'sceneAuthenticity': 'Autenticità scena',
      'aiProofLevel': 'Livello prova AI',
      'audio': 'Audio',
      'videoPlayerTitle': 'Player SIGILLUM',
      'selectVideoPrompt': 'Seleziona un video',
      'loadVideo': 'CARICA VIDEO',
      'loadHcv': 'CARICA HCV',
      'videoLoaded': 'Video caricato',
      'certificateLoaded': 'Certificato caricato',
      'noCertificate': 'Nessun certificato',
      'invalidCertificate': 'Certificato non valido',
      'hcvNotCompatible': 'HCV non compatibile con questo video',
      'videoModified': 'Video modificato',
      'audioTrust': 'Fiducia audio',
      'textWritePrompt': 'Scrivi un testo da certificare',
      'enterText': 'Inserisci un testo',
      'creatingTextCertificate': 'Creazione certificato testo...',
      'textCertified': 'Testo certificato e verificato',
      'certificateCreatedInvalid': 'Certificato creato ma NON valido',
      'textCertificateTitle': 'Certifica testo HCV',
      'textToCertify': 'Testo da certificare',
      'certifyTextButton': 'Crea e Certifica testo',
      'creating': 'CREAZIONE...',
      'newText': 'CREA NUOVO TESTO',
      'verifiableTextCreated': 'Testo verificabile creato',
      'copyHcvId': 'COPIA HCV-ID',
      'copySocialText': 'COPIA TESTO SOCIAL',
      'shareTextPost': 'CONDIVIDI TESTO COME POST',
      'shareTxtCertificate': 'CONDIVIDI TXT + CERTIFICATO HCV',
      'certificate': 'Certificato',
      'cameraTitle': 'Camera SIGILLUM',
      'createdFiles': 'File creati',
      'shareContent': 'CONDIVIDI CONTENUTO',
      'shareOfflinePack': 'CONDIVIDI HCVPACK OFFLINE',
      'photo': 'FOTO',
      'video': 'VIDEO',
      'photoMode': 'MODALITÀ FOTO',
      'videoMode': 'MODALITÀ VIDEO',
      'certificateVerifiedLabel': 'CERTIFICATO VERIFICATO',
      'notVerifiedLabel': 'NON VERIFICATO',
      'hcvIdCopied': 'HCV-ID copiato',
      'socialTextCopied': 'Testo social copiato',
      'verifiedTextShare': 'Testo certificato SIGILLUM',
      'openResourceFailed': 'Impossibile aprire questa risorsa.',
      'account': 'Account',
      'recording': 'REGISTRAZIONE IN CORSO',
      'cancel': 'ANNULLA',
      'secureOriginalsTitle': 'Originali protetti',
      'secureOriginalsIntro': 'Gli originali creati con SIGILLUM restano cifrati nell’area privata dell’app. Per visualizzarli o condividerli vengono decifrati solo temporaneamente.',
      'secureOriginalsEmpty': 'Non ci sono ancora originali protetti su questo dispositivo.',
      'secureOriginalsLoadError': 'Impossibile caricare gli originali protetti',
      'secureOriginalsViewError': 'Impossibile aprire l’originale',
      'secureOriginalsShareTitle': 'Condividi originale SIGILLUM',
      'secureOriginalsShareDisclosure': 'Prima di aprire il menu di condivisione, SIGILLUM verifica l’originale e registra la copia di riferimento sul canale ufficiale SIGILLUM. Se la pubblicazione del riferimento non riesce, il file non viene rilasciato al social.',
      'secureOriginalsRightsConfirm': 'Confermo di disporre dei diritti e delle autorizzazioni necessari per pubblicare questo contenuto.',
      'secureOriginalsMonetization': 'Autorizzo l’eventuale monetizzazione della copia di riferimento.',
      'secureOriginalsMonetizationHint': 'Facoltativo e disattivato per impostazione iniziale.',
      'secureOriginalsContinueShare': 'CONTINUA E CONDIVIDI',
      'secureOriginalsPublishingReference': 'Verifica dell’originale e pubblicazione della copia di riferimento in corso...',
      'secureOriginalsReferenceReady': 'Copia di riferimento registrata. Apertura del menu di condivisione...',
      'secureOriginalsShareText': 'Contenuto certificato SIGILLUM',
      'secureOriginalsShareComplete': 'Condivisione completata o chiusa.',
      'secureOriginalsShareBlocked': 'Condivisione bloccata',
      'secureOriginalsReferencePublished': 'Copia di riferimento pubblicata',
      'secureOriginalsReferencePending': 'Copia di riferimento non ancora pubblicata',
      'secureOriginalsView': 'VISUALIZZA',
      'secureOriginalsShare': 'CONDIVIDI',
      'secureOriginalsViewerTitle': 'Originale SIGILLUM',
      'secureOriginalStored': 'Originale e HCVPACK cifrati nell’area protetta SIGILLUM.',
      'secureOriginalsOpen': 'APRI ORIGINALI PROTETTI',
      'secureOriginalsHomeSubtitle': 'Visualizza e condividi solo attraverso SIGILLUM; il riferimento ufficiale viene registrato prima dell’uscita verso i social.',
      'verifiedOriginalsTitle': 'SIGILLUM Verified Originals',
      'verifiedOriginalsSubtitle': 'Verifica un HCV-ID, un file o guarda la copia di riferimento ufficiale.',
    },
    'en': {
      'identity': 'Identity',
      'accountTitle': 'ACCOUNT',
      'accountSubtitle': 'Profile, identity, KYC, security and data.',
      'headline': 'Technical proof for content created by real people.',
      'subtitle':
          'SIGILLUM links photos, videos and text to an HCV-ID, technical identity, file fingerprint, signed certificate and online Registry. Changes remain detectable.',
      'certifyMediaTitle': 'Create and certify a photo or video',
      'certifyMediaSubtitle':
          'Capture or record and create the HCV certificate.',
      'certifyTextTitle': 'Create and Certify Text',
      'certifyTextSubtitle': 'Create verifiable text with an HCV-ID.',
      'verifyTitle': 'Verify content',
      'verifySubtitle': 'Open a file, HCVPACK or verify from Registry.',
      'infoTitle': 'Information and privacy',
      'infoSubtitle': 'Checks, limits, terms and support.',
      'quickGuideTitle': 'How to use SIGILLUM',
      'quickGuideSubtitle':
          'Quick guide: camera, coordinates, flash, zoom, verification and captions',
      'quickGuideTooltip': 'How to use',
      'trustChain': 'Control chain',
      'controls': 'SIGILLUM checks',
      'capture': 'Capture',
      'captureText': 'created in app',
      'fingerprint': 'Fingerprint',
      'fingerprintText': 'file hash',
      'identityStep': 'Identity',
      'identityText': 'creator linked',
      'signature': 'Signature',
      'signatureText': 'protected certificate',
      'registry': 'Registry',
      'registryText': 'online verification',
      'checkIntegrity': 'File integrity and certificate consistency',
      'checkSignature': 'Digital certificate signature',
      'checkWatermark': 'Visible watermark in published content',
      'checkRegistry': 'Online Registry for future verification',
      'checkScreen': 'Screen replay risk check',
      'checkSocial': 'Recompressed-copy compatibility: image fingerprint for photos; visual and audio fingerprints for videos',
      'socialVerifyTitle': 'Verify from social media',
      'socialVerifyStep1':
          'When you see content on Facebook, WhatsApp, Messenger or other social apps, open Share.',
      'socialVerifyStep2': 'Choose SIGILLUM from the available apps.',
      'socialVerifyStep3':
          'SIGILLUM uses the HCV-ID or visible watermark to identify the Registry certificate; for a recompressed copy it then checks the fingerprints required for that media type.',
      'socialVerifyStep4':
          'If the content is certified, you see provenance, integrity and technical identity; modern videos verify visual and audio compatibility separately.',
      'legalPageTitle': 'Information',
      'legalIntro':
          'SIGILLUM creates verifiable technical proof linking content, HCV-ID, technical creator identity, file fingerprint and online Registry.',
      'legalControls': 'Checks performed',
      'legalData': 'Data processed',
      'legalLimits': 'Service limits',
      'data1': 'content created or selected by the user',
      'data2': 'HCV-ID and cryptographic file fingerprint',
      'data3': 'technical metadata required for verification',
      'data4': 'technical creator identity, when configured',
      'limit1':
          'SIGILLUM verifies technical provenance and integrity; it does not replace a legal expert report.',
      'limit2':
          'A screen-risk warning means caution, not automatic proof of falsification.',
      'limit3': 'Online verification requires the Registry to be reachable.',
      'privacyPolicy': 'Privacy policy',
      'terms': 'Terms of service',
      'support': 'Support and data deletion',
      'deleteData': 'Data deletion',
      'copied': 'Copied',
      'technicalIdentityTitle': 'Technical identity',
      'technicalIdentityHeading': 'SIGILLUM technical identity',
      'technicalIdentityBody':
          'SIGILLUM links content to a device technical key, a user-declared name and, when completed, a document KYC verification.',
      'declaredName': 'Declared name',
      'saveName': 'SAVE NAME',
      'loadingTechnicalIdentity': 'Loading technical identity...',
      'technicalIdentityLoaded': 'Technical identity loaded',
      'enterDeclaredName': 'Enter the declared name',
      'declaredNameSaved': 'Declared name saved',
      'technicalCreatorId': 'Technical creator ID',
      'deviceKeyFingerprint': 'Device key fingerprint',
      'technicalIdentityFingerprint': 'Technical identity fingerprint',
      'identityAssurance': 'Identity assurance',
      'legalIdentity': 'Legal identity',
      'verifiedLegalName': 'Verified legal name',
      'verifiedLegalCountry': 'Document country',
      'startKyc': 'Start identity verification',
      'kycExplanation':
          'Document KYC will be handled by an external provider. SIGILLUM will store only the minimum verification status.',
      'kycStarting': 'Starting identity verification...',
      'kycLinkReady': 'KYC link ready. Open it in your browser:',
      'kycConfiguredNoUrl':
          'KYC is configured, but the server did not return a link.',
      'kycNotAvailable': 'KYC not available yet',
      'kycOpening': 'Opening identity verification...',
      'refreshKyc': 'Refresh verification status',
      'kycRefreshing': 'Refreshing verification status...',
      'kycNoSession': 'No KYC session started.',
      'kycVerified': 'Legal identity verified.',
      'kycStatus': 'KYC status',
      'kycStatusLabel': 'KYC status',
      'kycStatusUnavailable': 'KYC status unavailable',
      'kycRequiresInputHint':
          'Verification incomplete: tap Start identity verification to resume the same Stripe session.',
      'privacy': 'Privacy',
      'technicalProof': 'Technical proof',
      'notGeneratedYet': 'Not generated yet',
      'verifyContentHeading': 'Verify content',
      'supportedFiles': 'Supported:\n.hcvpack, .hcv, photos, videos, text, PDF',
      'selectFile': 'SELECT FILE',
      'selectFileToVerify': 'Select a file to verify',
      'noFileSelected': 'No file selected',
      'filePathUnavailable': 'File path unavailable',
      'fileSelected': 'Selected file',
      'importError': 'Import error',
      'analyzingFile': 'Analyzing file...',
      'fileNotFound': 'File not found',
      'unknownFormat': 'Unknown format',
      'selectHcv': 'SELECT HCV',
      'selectOriginalMedia': 'SELECT ORIGINAL MEDIA',
      'verifyFromRegistry': 'VERIFY FROM REGISTRY',
      'verifyingShort': 'VERIFYING...',
      'selectHcvFile': 'Select HCV file',
      'selectHcvExtension': 'Select a .hcv file',
      'selectHcvFirst': 'Select an HCV file first',
      'verifying': 'Verifying...',
      'certificateValid': 'Certificate valid',
      'certificateInvalid': 'Certificate invalid',
      'issuer': 'Issuer',
      'hcvpackDetails': 'HCVPACK verification details',
      'hcvpackSelect': 'Select .hcvpack file',
      'hcvpackInvalid': 'Invalid HCV certificate',
      'hcvpackIncomplete': 'Incomplete HCV certificate',
      'verificationComplete': 'Verification complete',
      'identityUnavailable': 'Identity not available',
      'fileType': 'File type',
      'trustLevel': 'Trust level',
      'liveCapture': 'Live capture',
      'screenReplayRisk': 'Screen replay risk',
      'syntheticRisk': 'Synthetic risk',
      'sceneAuthenticity': 'Scene authenticity',
      'aiProofLevel': 'AI proof level',
      'audio': 'Audio',
      'videoPlayerTitle': 'SIGILLUM Player',
      'selectVideoPrompt': 'Select a video',
      'loadVideo': 'LOAD VIDEO',
      'loadHcv': 'LOAD HCV',
      'videoLoaded': 'Video loaded',
      'certificateLoaded': 'Certificate loaded',
      'noCertificate': 'No certificate selected',
      'invalidCertificate': 'Invalid certificate',
      'hcvNotCompatible': 'HCV is not compatible with this video',
      'videoModified': 'Video has been modified',
      'audioTrust': 'Audio trust',
      'textWritePrompt': 'Write text to certify',
      'enterText': 'Enter text',
      'creatingTextCertificate': 'Creating text certificate...',
      'textCertified': 'Text certified and verified',
      'certificateCreatedInvalid': 'Certificate created but NOT valid',
      'textCertificateTitle': 'Certify HCV text',
      'textToCertify': 'Text to certify',
      'certifyTextButton': 'Create and Certify Text',
      'creating': 'CREATING...',
      'newText': 'CREATE NEW TEXT',
      'verifiableTextCreated': 'Verifiable text created',
      'copyHcvId': 'COPY HCV-ID',
      'copySocialText': 'COPY SOCIAL TEXT',
      'shareTextPost': 'SHARE TEXT AS POST',
      'shareTxtCertificate': 'SHARE TXT + HCV CERTIFICATE',
      'certificate': 'Certificate',
      'cameraTitle': 'SIGILLUM Camera',
      'createdFiles': 'Created files',
      'shareContent': 'SHARE CONTENT',
      'shareOfflinePack': 'SHARE OFFLINE HCVPACK',
      'photo': 'PHOTO',
      'video': 'VIDEO',
      'photoMode': 'PHOTO MODE',
      'videoMode': 'VIDEO MODE',
      'certificateVerifiedLabel': 'CERTIFICATE VERIFIED',
      'notVerifiedLabel': 'NOT VERIFIED',
      'hcvIdCopied': 'HCV-ID copied',
      'socialTextCopied': 'Social text copied',
      'verifiedTextShare': 'SIGILLUM certified text',
      'openResourceFailed': 'Unable to open this resource.',
      'account': 'Account',
      'recording': 'RECORDING',
      'cancel': 'CANCEL',
      'secureOriginalsTitle': 'Protected originals',
      'secureOriginalsIntro': 'Originals created with SIGILLUM remain encrypted inside the app’s private area. They are decrypted only temporarily for viewing or sharing.',
      'secureOriginalsEmpty': 'There are no protected originals on this device yet.',
      'secureOriginalsLoadError': 'Unable to load protected originals',
      'secureOriginalsViewError': 'Unable to open the original',
      'secureOriginalsShareTitle': 'Share SIGILLUM original',
      'secureOriginalsShareDisclosure': 'Before the share sheet opens, SIGILLUM verifies the original and registers the reference copy on the official SIGILLUM channel. If reference publication fails, the file is not released to the social platform.',
      'secureOriginalsRightsConfirm': 'I confirm that I have the rights and permissions required to publish this content.',
      'secureOriginalsMonetization': 'I authorize possible monetization of the reference copy.',
      'secureOriginalsMonetizationHint': 'Optional and disabled by default.',
      'secureOriginalsContinueShare': 'CONTINUE AND SHARE',
      'secureOriginalsPublishingReference': 'Verifying the original and publishing the reference copy...',
      'secureOriginalsReferenceReady': 'Reference copy registered. Opening the share sheet...',
      'secureOriginalsShareText': 'SIGILLUM certified content',
      'secureOriginalsShareComplete': 'Sharing completed or closed.',
      'secureOriginalsShareBlocked': 'Sharing blocked',
      'secureOriginalsReferencePublished': 'Reference copy published',
      'secureOriginalsReferencePending': 'Reference copy not yet published',
      'secureOriginalsView': 'VIEW',
      'secureOriginalsShare': 'SHARE',
      'secureOriginalsViewerTitle': 'SIGILLUM original',
      'secureOriginalStored': 'Original and HCVPACK encrypted in the protected SIGILLUM area.',
      'secureOriginalsOpen': 'OPEN PROTECTED ORIGINALS',
      'secureOriginalsHomeSubtitle': 'View and share only through SIGILLUM; the official reference is registered before a file is released to social platforms.',
      'verifiedOriginalsTitle': 'SIGILLUM Verified Originals',
      'verifiedOriginalsSubtitle': 'Check an HCV-ID or file, or view the official reference copy.',
    },
    'es': {
      'identity': 'Identidad',
      'accountTitle': 'CUENTA',
      'accountSubtitle': 'Perfil, identidad, KYC, seguridad y datos.',
      'headline': 'Prueba tecnica para contenidos creados por personas reales.',
      'subtitle':
          'SIGILLUM vincula fotos, videos y textos a un HCV-ID, identidad tecnica, huella del archivo, certificado firmado y Registry online. Las modificaciones siguen siendo detectables.',
      'certifyMediaTitle': 'Crear y certificar una foto o un vídeo',
      'certifyMediaSubtitle': 'Captura o graba y crea el certificado HCV.',
      'certifyTextTitle': 'Crear y certificar texto',
      'certifyTextSubtitle': 'Crea un texto verificable con HCV-ID.',
      'verifyTitle': 'Verificar contenido',
      'verifySubtitle': 'Abre un archivo, HCVPACK o verifica en Registry.',
      'infoTitle': 'Informacion y privacidad',
      'infoSubtitle': 'Controles, limites, terminos y soporte.',
      'quickGuideTitle': 'Cómo usar SIGILLUM',
      'quickGuideSubtitle':
          'Guía rápida: cámara, coordenadas, flash, zoom, verificación y subtítulos',
      'quickGuideTooltip': 'Cómo se usa',
      'trustChain': 'Cadena de control',
      'controls': 'Controles SIGILLUM',
      'capture': 'Captura',
      'captureText': 'creada en la app',
      'fingerprint': 'Huella',
      'fingerprintText': 'hash del archivo',
      'identityStep': 'Identidad',
      'identityText': 'creador vinculado',
      'signature': 'Firma',
      'signatureText': 'certificado protegido',
      'registry': 'Registry',
      'registryText': 'verificacion online',
      'checkIntegrity': 'Integridad del archivo y coherencia del certificado',
      'checkSignature': 'Firma digital del certificado',
      'checkWatermark': 'Marca visible en el contenido publicado',
      'checkRegistry': 'Registry online para verificacion futura',
      'checkScreen': 'Control de riesgo de regrabacion de pantalla',
      'checkSocial': 'Compatibilidad de copias recomprimidas: huella de imagen para fotos; huellas visual y de audio para vídeos',
      'socialVerifyTitle': 'Verificacion desde redes sociales',
      'socialVerifyStep1':
          'Cuando veas contenido en Facebook, WhatsApp, Messenger u otras redes, abre Compartir.',
      'socialVerifyStep2': 'Elige SIGILLUM entre las apps disponibles.',
      'socialVerifyStep3':
          'SIGILLUM usa el HCV-ID o la marca visible para identificar el certificado en Registry; después comprueba las huellas previstas para ese tipo de media si se trata de una copia recomprimida.',
      'socialVerifyStep4':
          'Si el contenido está certificado, verás procedencia, integridad e identidad técnica; en los vídeos modernos se comprueba por separado la compatibilidad visual y de audio.',
      'legalPageTitle': 'Informacion',
      'legalIntro':
          'SIGILLUM crea una prueba tecnica verificable que vincula contenido, HCV-ID, identidad tecnica del creador, huella del archivo y Registry online.',
      'legalControls': 'Controles realizados',
      'legalData': 'Datos tratados',
      'legalLimits': 'Limites del servicio',
      'data1': 'contenido creado o seleccionado por el usuario',
      'data2': 'HCV-ID y huella criptografica del archivo',
      'data3': 'metadatos tecnicos necesarios para la verificacion',
      'data4': 'identidad tecnica del creador, si esta configurada',
      'limit1':
          'SIGILLUM verifica procedencia tecnica e integridad; no sustituye un informe pericial legal.',
      'limit2':
          'Una advertencia de riesgo de pantalla indica cautela, no prueba automatica de falsedad.',
      'limit3':
          'La verificacion online requiere que el Registry este accesible.',
      'privacyPolicy': 'Politica de privacidad',
      'terms': 'Terminos del servicio',
      'support': 'Soporte y eliminacion de datos',
      'deleteData': 'Eliminacion de datos',
      'copied': 'Copiado',
      'technicalIdentityTitle': 'Identidad tecnica',
      'technicalIdentityHeading': 'Identidad tecnica SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM vincula el contenido a una clave tecnica del dispositivo, a un nombre declarado y, si se completa, a una verificacion documental KYC.',
      'declaredName': 'Nombre declarado',
      'saveName': 'GUARDAR NOMBRE',
      'loadingTechnicalIdentity': 'Cargando identidad tecnica...',
      'technicalIdentityLoaded': 'Identidad tecnica cargada',
      'enterDeclaredName': 'Introduce el nombre declarado',
      'declaredNameSaved': 'Nombre declarado guardado',
      'technicalCreatorId': 'ID tecnico del creador',
      'deviceKeyFingerprint': 'Huella de clave del dispositivo',
      'technicalIdentityFingerprint': 'Huella de identidad tecnica',
      'identityAssurance': 'Garantia de identidad',
      'legalIdentity': 'Identidad legal',
      'verifiedLegalName': 'Nombre legal verificado',
      'verifiedLegalCountry': 'Pais del documento',
      'startKyc': 'Iniciar verificacion de identidad',
      'kycExplanation':
          'El KYC documental sera gestionado por un proveedor externo. SIGILLUM guardara solo el estado minimo de verificacion.',
      'kycStarting': 'Iniciando verificacion de identidad...',
      'kycLinkReady': 'Link KYC listo. Abrelo en el navegador:',
      'kycConfiguredNoUrl':
          'KYC configurado, pero el servidor no devolvio un link.',
      'kycNotAvailable': 'KYC aun no disponible',
      'kycOpening': 'Abriendo verificacion de identidad...',
      'refreshKyc': 'Actualizar estado de verificacion',
      'kycRefreshing': 'Actualizando estado de verificacion...',
      'kycNoSession': 'No hay ninguna sesion KYC iniciada.',
      'kycVerified': 'Identidad legal verificada.',
      'kycStatus': 'Estado KYC',
      'kycStatusLabel': 'Estado KYC',
      'kycStatusUnavailable': 'Estado KYC no disponible',
      'kycRequiresInputHint':
          'Verificacion incompleta: toca Iniciar verificacion de identidad para reanudar la misma sesion de Stripe.',
      'privacy': 'Privacidad',
      'technicalProof': 'Prueba tecnica',
      'notGeneratedYet': 'Aun no generado',
      'verifyContentHeading': 'Verificar contenido',
      'supportedFiles':
          'Soportados:\n.hcvpack, .hcv, fotos, videos, texto, PDF',
      'selectFile': 'SELECCIONAR ARCHIVO',
      'selectFileToVerify': 'Selecciona un archivo para verificar',
      'noFileSelected': 'Ningun archivo seleccionado',
      'filePathUnavailable': 'Ruta del archivo no disponible',
      'fileSelected': 'Archivo seleccionado',
      'importError': 'Error de importacion',
      'analyzingFile': 'Analizando archivo...',
      'fileNotFound': 'Archivo no encontrado',
      'unknownFormat': 'Formato no reconocido',
      'selectHcv': 'SELECCIONAR HCV',
      'selectOriginalMedia': 'SELECCIONAR MEDIA ORIGINAL',
      'verifyFromRegistry': 'VERIFICAR EN REGISTRY',
      'verifyingShort': 'VERIFICANDO...',
      'selectHcvFile': 'Selecciona archivo HCV',
      'selectHcvExtension': 'Selecciona un archivo .hcv',
      'selectHcvFirst': 'Selecciona primero un archivo HCV',
      'verifying': 'Verificando...',
      'certificateValid': 'Certificado valido',
      'certificateInvalid': 'Certificado no valido',
      'issuer': 'Emisor',
      'hcvpackDetails': 'Detalles de verificacion HCVPACK',
      'hcvpackSelect': 'Selecciona archivo .hcvpack',
      'hcvpackInvalid': 'Certificado HCV no valido',
      'hcvpackIncomplete': 'Certificado HCV incompleto',
      'verificationComplete': 'Verificacion completada',
      'identityUnavailable': 'Identidad no disponible',
      'fileType': 'Tipo de archivo',
      'trustLevel': 'Nivel de confianza',
      'liveCapture': 'Captura en vivo',
      'screenReplayRisk': 'Riesgo de pantalla',
      'syntheticRisk': 'Riesgo sintetico',
      'sceneAuthenticity': 'Autenticidad de escena',
      'aiProofLevel': 'Nivel de prueba IA',
      'audio': 'Audio',
      'videoPlayerTitle': 'Reproductor SIGILLUM',
      'selectVideoPrompt': 'Selecciona un vídeo',
      'loadVideo': 'CARGAR VÍDEO',
      'loadHcv': 'CARGAR HCV',
      'videoLoaded': 'Vídeo cargado',
      'certificateLoaded': 'Certificado cargado',
      'noCertificate': 'No se ha seleccionado un certificado',
      'invalidCertificate': 'Certificado no válido',
      'hcvNotCompatible': 'El HCV no es compatible con este vídeo',
      'videoModified': 'El vídeo ha sido modificado',
      'audioTrust': 'Confianza audio',
      'textWritePrompt': 'Escribe un texto para certificar',
      'enterText': 'Introduce un texto',
      'creatingTextCertificate': 'Creando certificado de texto...',
      'textCertified': 'Texto certificado y verificado',
      'certificateCreatedInvalid': 'Certificado creado pero NO valido',
      'textCertificateTitle': 'Certificar texto HCV',
      'textToCertify': 'Texto para certificar',
      'certifyTextButton': 'Crear y certificar texto',
      'creating': 'CREANDO...',
      'newText': 'CREAR NUEVO TEXTO',
      'verifiableTextCreated': 'Texto verificable creado',
      'copyHcvId': 'COPIAR HCV-ID',
      'copySocialText': 'COPIAR TEXTO SOCIAL',
      'shareTextPost': 'COMPARTIR TEXTO COMO POST',
      'shareTxtCertificate': 'COMPARTIR TXT + CERTIFICADO HCV',
      'certificate': 'Certificado',
      'cameraTitle': 'Camara SIGILLUM',
      'createdFiles': 'Archivos creados',
      'shareContent': 'COMPARTIR CONTENIDO',
      'shareOfflinePack': 'COMPARTIR HCVPACK OFFLINE',
      'photo': 'FOTO',
      'video': 'VIDEO',
      'photoMode': 'MODO FOTO',
      'videoMode': 'MODO VIDEO',
      'certificateVerifiedLabel': 'CERTIFICADO VERIFICADO',
      'notVerifiedLabel': 'NO VERIFICADO',
      'hcvIdCopied': 'HCV-ID copiado',
      'socialTextCopied': 'Texto social copiado',
      'verifiedTextShare': 'Texto certificado por SIGILLUM',
      'openResourceFailed': 'No se puede abrir este recurso.',
      'account': 'Cuenta',
      'recording': 'GRABANDO',
      'cancel': 'CANCELAR',
      'secureOriginalsTitle': 'Originales protegidos',
      'secureOriginalsIntro': 'Los originales creados con SIGILLUM permanecen cifrados en el área privada de la app. Solo se descifran temporalmente para verlos o compartirlos.',
      'secureOriginalsEmpty': 'Todavía no hay originales protegidos en este dispositivo.',
      'secureOriginalsLoadError': 'No se pueden cargar los originales protegidos',
      'secureOriginalsViewError': 'No se puede abrir el original',
      'secureOriginalsShareTitle': 'Compartir original SIGILLUM',
      'secureOriginalsShareDisclosure': 'Antes de abrir el menú de compartir, SIGILLUM verifica el original y registra la copia de referencia en el canal oficial de SIGILLUM. Si falla la publicación de la referencia, el archivo no se entrega a la red social.',
      'secureOriginalsRightsConfirm': 'Confirmo que dispongo de los derechos y autorizaciones necesarios para publicar este contenido.',
      'secureOriginalsMonetization': 'Autorizo la posible monetización de la copia de referencia.',
      'secureOriginalsMonetizationHint': 'Opcional y desactivada por defecto.',
      'secureOriginalsContinueShare': 'CONTINUAR Y COMPARTIR',
      'secureOriginalsPublishingReference': 'Verificando el original y publicando la copia de referencia...',
      'secureOriginalsReferenceReady': 'Copia de referencia registrada. Abriendo el menú de compartir...',
      'secureOriginalsShareText': 'Contenido certificado SIGILLUM',
      'secureOriginalsShareComplete': 'Compartición completada o cerrada.',
      'secureOriginalsShareBlocked': 'Compartición bloqueada',
      'secureOriginalsReferencePublished': 'Copia de referencia publicada',
      'secureOriginalsReferencePending': 'Copia de referencia aún no publicada',
      'secureOriginalsView': 'VER',
      'secureOriginalsShare': 'COMPARTIR',
      'secureOriginalsViewerTitle': 'Original SIGILLUM',
      'secureOriginalStored': 'Original y HCVPACK cifrados en el área protegida de SIGILLUM.',
      'secureOriginalsOpen': 'ABRIR ORIGINALES PROTEGIDOS',
      'secureOriginalsHomeSubtitle': 'Visualiza y comparte solo mediante SIGILLUM; la referencia oficial se registra antes de entregar el archivo a una red social.',
      'verifiedOriginalsTitle': 'SIGILLUM Verified Originals',
      'verifiedOriginalsSubtitle': 'Verifica un HCV-ID o un archivo, o consulta la copia de referencia oficial.',
    },
    'ru': {
      'identity': 'Идентичность',
      'accountTitle': 'АККАУНТ',
      'accountSubtitle': 'Профиль, личность, KYC, безопасность и данные.',
      'headline': 'Техническое доказательство для контента, созданного людьми.',
      'subtitle':
          'SIGILLUM связывает фото, видео и текст с HCV-ID, технической идентичностью, отпечатком файла, подписанным сертификатом и онлайн Registry. Изменения остаются обнаруживаемыми.',
      'certifyMediaTitle': 'Создать и сертифицировать фото или видео',
      'certifyMediaSubtitle': 'Снимите материал и создайте HCV-сертификат.',
      'certifyTextTitle': 'Создать и сертифицировать текст',
      'certifyTextSubtitle': 'Создайте проверяемый текст с HCV-ID.',
      'verifyTitle': 'Проверить контент',
      'verifySubtitle': 'Откройте файл, HCVPACK или проверьте через Registry.',
      'infoTitle': 'Информация и конфиденциальность',
      'infoSubtitle': 'Проверки, ограничения, условия и поддержка.',
      'quickGuideTitle': 'Как пользоваться SIGILLUM',
      'quickGuideSubtitle':
          'Краткое руководство: камера, координаты, вспышка, зум, проверка и субтитры',
      'quickGuideTooltip': 'Как пользоваться',
      'trustChain': 'Цепочка контроля',
      'controls': 'Проверки SIGILLUM',
      'capture': 'Съемка',
      'captureText': 'создано в приложении',
      'fingerprint': 'Отпечаток',
      'fingerprintText': 'хэш файла',
      'identityStep': 'Идентичность',
      'identityText': 'автор связан',
      'signature': 'Подпись',
      'signatureText': 'защищенный сертификат',
      'registry': 'Registry',
      'registryText': 'онлайн-проверка',
      'checkIntegrity': 'Целостность файла и соответствие сертификату',
      'checkSignature': 'Цифровая подпись сертификата',
      'checkWatermark': 'Видимая метка в опубликованном контенте',
      'checkRegistry': 'Онлайн Registry для будущей проверки',
      'checkScreen': 'Проверка риска пересъемки с экрана',
      'checkSocial': 'Совместимость после перекодирования: отпечаток изображения для фото; визуальный и аудиоотпечатки для видео',
      'socialVerifyTitle': 'Проверка из соцсетей',
      'socialVerifyStep1':
          'Когда вы видите контент в Facebook, WhatsApp, Messenger или другой соцсети, откройте Поделиться.',
      'socialVerifyStep2': 'Выберите SIGILLUM среди доступных приложений.',
      'socialVerifyStep3':
          'SIGILLUM использует HCV-ID или видимую метку для поиска сертификата в Registry; для перекодированной копии затем проверяются отпечатки, предусмотренные для этого типа медиа.',
      'socialVerifyStep4':
          'Если контент сертифицирован, отображаются происхождение, целостность и техническая идентичность; в современных видео визуальная и аудиосовместимость проверяются отдельно.',
      'legalPageTitle': 'Информация',
      'legalIntro':
          'SIGILLUM создает проверяемое техническое доказательство, связывающее контент, HCV-ID, техническую идентичность автора, отпечаток файла и онлайн Registry.',
      'legalControls': 'Выполняемые проверки',
      'legalData': 'Обрабатываемые данные',
      'legalLimits': 'Ограничения сервиса',
      'data1': 'контент, созданный или выбранный пользователем',
      'data2': 'HCV-ID и криптографический отпечаток файла',
      'data3': 'технические метаданные, необходимые для проверки',
      'data4': 'техническая идентичность автора, если настроена',
      'limit1':
          'SIGILLUM проверяет техническое происхождение и целостность; это не заменяет юридическую экспертизу.',
      'limit2':
          'Предупреждение о риске экрана означает осторожность, а не автоматическое доказательство подделки.',
      'limit3': 'Онлайн-проверка требует доступности Registry.',
      'privacyPolicy': 'Политика конфиденциальности',
      'terms': 'Условия сервиса',
      'support': 'Поддержка и удаление данных',
      'deleteData': 'Удаление данных',
      'copied': 'Скопировано',
      'technicalIdentityTitle': 'Техническая идентичность',
      'technicalIdentityHeading': 'Техническая идентичность SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM связывает контент с техническим ключом устройства, указанным именем и, если завершено, документальной проверкой KYC.',
      'declaredName': 'Указанное имя',
      'saveName': 'СОХРАНИТЬ ИМЯ',
      'loadingTechnicalIdentity': 'Загрузка технической идентичности...',
      'technicalIdentityLoaded': 'Техническая идентичность загружена',
      'enterDeclaredName': 'Введите указанное имя',
      'declaredNameSaved': 'Указанное имя сохранено',
      'technicalCreatorId': 'Технический ID автора',
      'deviceKeyFingerprint': 'Отпечаток ключа устройства',
      'technicalIdentityFingerprint': 'Отпечаток технической идентичности',
      'identityAssurance': 'Уровень идентичности',
      'legalIdentity': 'Юридическая идентичность',
      'verifiedLegalName': 'Verified legal name',
      'verifiedLegalCountry': 'Document country',
      'startKyc': 'Начать проверку личности',
      'kycExplanation':
          'Проверка документов KYC будет выполняться внешним провайдером. SIGILLUM сохранит только минимальный статус проверки.',
      'kycStarting': 'Запуск проверки личности...',
      'kycLinkReady': 'Ссылка KYC готова. Откройте ее в браузере:',
      'kycConfiguredNoUrl': 'KYC настроен, но сервер не вернул ссылку.',
      'kycNotAvailable': 'KYC пока недоступен',
      'kycOpening': 'Открываю проверку личности...',
      'refreshKyc': 'Обновить статус проверки',
      'kycRefreshing': 'Обновление статуса проверки...',
      'kycNoSession': 'Сессия KYC не запущена.',
      'kycVerified': 'Юридическая личность подтверждена.',
      'kycStatus': 'Статус KYC',
      'kycStatusLabel': 'Статус KYC',
      'kycStatusUnavailable': 'Статус KYC недоступен',
      'kycRequiresInputHint':
          'Verification incomplete: reopen identity verification to resume the same Stripe session.',
      'privacy': 'Конфиденциальность',
      'technicalProof': 'Техническое доказательство',
      'notGeneratedYet': 'Еще не создано',
      'verifyContentHeading': 'Проверить контент',
      'supportedFiles':
          'Поддерживаются:\n.hcvpack, .hcv, фото, видео, текст, PDF',
      'selectFile': 'ВЫБРАТЬ ФАЙЛ',
      'selectFileToVerify': 'Выберите файл для проверки',
      'noFileSelected': 'Файл не выбран',
      'filePathUnavailable': 'Путь к файлу недоступен',
      'fileSelected': 'Выбранный файл',
      'importError': 'Ошибка импорта',
      'analyzingFile': 'Анализ файла...',
      'fileNotFound': 'Файл не найден',
      'unknownFormat': 'Неизвестный формат',
      'selectHcv': 'ВЫБРАТЬ HCV',
      'selectOriginalMedia': 'ВЫБРАТЬ ОРИГИНАЛ',
      'verifyFromRegistry': 'ПРОВЕРИТЬ В REGISTRY',
      'verifyingShort': 'ПРОВЕРКА...',
      'selectHcvFile': 'Выберите HCV-файл',
      'selectHcvExtension': 'Выберите файл .hcv',
      'selectHcvFirst': 'Сначала выберите HCV-файл',
      'verifying': 'Проверка...',
      'certificateValid': 'Сертификат действителен',
      'certificateInvalid': 'Сертификат недействителен',
      'issuer': 'Эмитент',
      'hcvpackDetails': 'Детали проверки HCVPACK',
      'hcvpackSelect': 'Выберите файл .hcvpack',
      'hcvpackInvalid': 'Недействительный HCV-сертификат',
      'hcvpackIncomplete': 'Неполный HCV-сертификат',
      'verificationComplete': 'Проверка завершена',
      'identityUnavailable': 'Идентичность недоступна',
      'fileType': 'Тип файла',
      'trustLevel': 'Уровень доверия',
      'liveCapture': 'Живая съемка',
      'screenReplayRisk': 'Риск пересъемки экрана',
      'syntheticRisk': 'Синтетический риск',
      'sceneAuthenticity': 'Подлинность сцены',
      'aiProofLevel': 'Уровень AI-доказательства',
      'audio': 'Аудио',
      'videoPlayerTitle': 'Проигрыватель SIGILLUM',
      'selectVideoPrompt': 'Выберите видео',
      'loadVideo': 'ЗАГРУЗИТЬ ВИДЕО',
      'loadHcv': 'ЗАГРУЗИТЬ HCV',
      'videoLoaded': 'Видео загружено',
      'certificateLoaded': 'Сертификат загружен',
      'noCertificate': 'Сертификат не выбран',
      'invalidCertificate': 'Недействительный сертификат',
      'hcvNotCompatible': 'HCV не соответствует этому видео',
      'videoModified': 'Видео было изменено',
      'audioTrust': 'Доверие к аудио',
      'textWritePrompt': 'Напишите текст для сертификации',
      'enterText': 'Введите текст',
      'creatingTextCertificate': 'Создание текстового сертификата...',
      'textCertified': 'Текст сертифицирован и проверен',
      'certificateCreatedInvalid': 'Сертификат создан, но НЕ действителен',
      'textCertificateTitle': 'Сертифицировать текст HCV',
      'textToCertify': 'Текст для сертификации',
      'certifyTextButton': 'Создать и сертифицировать текст',
      'creating': 'СОЗДАНИЕ...',
      'newText': 'СОЗДАТЬ НОВЫЙ ТЕКСТ',
      'verifiableTextCreated': 'Проверяемый текст создан',
      'copyHcvId': 'КОПИРОВАТЬ HCV-ID',
      'copySocialText': 'КОПИРОВАТЬ ТЕКСТ ДЛЯ СОЦСЕТЕЙ',
      'shareTextPost': 'ПОДЕЛИТЬСЯ ТЕКСТОМ КАК ПОСТОМ',
      'shareTxtCertificate': 'ПОДЕЛИТЬСЯ TXT + HCV-СЕРТИФИКАТОМ',
      'certificate': 'Сертификат',
      'cameraTitle': 'Камера SIGILLUM',
      'createdFiles': 'Созданные файлы',
      'shareContent': 'ПОДЕЛИТЬСЯ КОНТЕНТОМ',
      'shareOfflinePack': 'ПОДЕЛИТЬСЯ HCVPACK OFFLINE',
      'photo': 'ФОТО',
      'video': 'ВИДЕО',
      'photoMode': 'РЕЖИМ ФОТО',
      'videoMode': 'РЕЖИМ ВИДЕО',
      'certificateVerifiedLabel': 'СЕРТИФИКАТ ПОДТВЕРЖДЁН',
      'notVerifiedLabel': 'НЕ ПОДТВЕРЖДЕНО',
      'hcvIdCopied': 'HCV-ID скопирован',
      'socialTextCopied': 'Текст для публикации скопирован',
      'verifiedTextShare': 'Сертифицированный SIGILLUM текст',
      'openResourceFailed': 'Не удалось открыть этот ресурс.',
      'account': 'Аккаунт',
      'recording': 'ИДЕТ ЗАПИСЬ',
      'cancel': 'ОТМЕНА',
      'secureOriginalsTitle': 'Защищённые оригиналы',
      'secureOriginalsIntro': 'Оригиналы, созданные в SIGILLUM, остаются зашифрованными в закрытой области приложения. Они временно расшифровываются только для просмотра или отправки.',
      'secureOriginalsEmpty': 'На этом устройстве пока нет защищённых оригиналов.',
      'secureOriginalsLoadError': 'Не удалось загрузить защищённые оригиналы',
      'secureOriginalsViewError': 'Не удалось открыть оригинал',
      'secureOriginalsShareTitle': 'Поделиться оригиналом SIGILLUM',
      'secureOriginalsShareDisclosure': 'Перед открытием меню «Поделиться» SIGILLUM проверяет оригинал и регистрирует эталонную копию на официальном канале SIGILLUM. Если публикация эталона не удалась, файл не передаётся социальной платформе.',
      'secureOriginalsRightsConfirm': 'Я подтверждаю наличие необходимых прав и разрешений на публикацию этого контента.',
      'secureOriginalsMonetization': 'Я разрешаю возможную монетизацию эталонной копии.',
      'secureOriginalsMonetizationHint': 'Необязательно и по умолчанию отключено.',
      'secureOriginalsContinueShare': 'ПРОДОЛЖИТЬ И ПОДЕЛИТЬСЯ',
      'secureOriginalsPublishingReference': 'Проверка оригинала и публикация эталонной копии...',
      'secureOriginalsReferenceReady': 'Эталонная копия зарегистрирована. Открывается меню «Поделиться»...',
      'secureOriginalsShareText': 'Сертифицированный контент SIGILLUM',
      'secureOriginalsShareComplete': 'Отправка завершена или закрыта.',
      'secureOriginalsShareBlocked': 'Отправка заблокирована',
      'secureOriginalsReferencePublished': 'Эталонная копия опубликована',
      'secureOriginalsReferencePending': 'Эталонная копия ещё не опубликована',
      'secureOriginalsView': 'ПРОСМОТР',
      'secureOriginalsShare': 'ПОДЕЛИТЬСЯ',
      'secureOriginalsViewerTitle': 'Оригинал SIGILLUM',
      'secureOriginalStored': 'Оригинал и HCVPACK зашифрованы в защищённой области SIGILLUM.',
      'secureOriginalsOpen': 'ОТКРЫТЬ ЗАЩИЩЁННЫЕ ОРИГИНАЛЫ',
      'secureOriginalsHomeSubtitle': 'Просматривайте и отправляйте только через SIGILLUM; официальный эталон регистрируется до передачи файла в социальную сеть.',
      'verifiedOriginalsTitle': 'SIGILLUM Verified Originals',
      'verifiedOriginalsSubtitle': 'Проверьте HCV-ID или файл либо откройте официальную эталонную копию.',
    },
  };
}
