import 'dart:ui';

class SigillumLanguage {
  const SigillumLanguage({
    required this.code,
    required this.name,
    required this.shortName,
  });

  final String code;
  final String name;
  final String shortName;
}

class SigillumCopy {
  static const languages = [
    SigillumLanguage(code: 'it', name: 'Italiano', shortName: 'IT'),
    SigillumLanguage(code: 'en', name: 'English', shortName: 'EN'),
    SigillumLanguage(code: 'es', name: 'Español', shortName: 'ES'),
    SigillumLanguage(code: 'ru', name: 'Русский', shortName: 'RU'),
  ];

  static String initialLanguageCode() {
    final localeCode = PlatformDispatcher.instance.locale.languageCode;
    return languages.any((language) => language.code == localeCode)
        ? localeCode
        : 'en';
  }

  static SigillumLanguage language(String code) {
    return languages.firstWhere(
      (language) => language.code == code,
      orElse: () => languages[1],
    );
  }

  static String t(String code, String key) {
    return (_copy[code] ?? _copy['en']!)[key] ?? _copy['en']![key] ?? key;
  }

  static const _copy = {
    'it': {
      'identity': 'Identità',
      'accountTitle': 'ACCOUNT',
      'accountSubtitle': 'Profilo, identità, KYC, sicurezza e dati.',
      'creatorEntitlementUnavailable':
          'Impossibile verificare l’abbonamento Creator. Riprova quando la connessione è disponibile.',
      'headline': 'Tu crei. SIGILLUM protegge l’origine.',
      'subtitle':
          'Scatta, registra o scrivi. SIGILLUM crea HCV-ID e certificato firmato, collega il contenuto al Creator e al dispositivo e lo rende verificabile nel tempo. Per foto e video registra il riferimento protetto prima del rilascio all’esterno.',
      'certifyMediaTitle': 'Crea e Certifica foto o video',
      'certifyMediaSubtitle': 'Scatta o registra. SIGILLUM certifica e protegge l’originale.',
      'certifyTextTitle': 'Crea e Certifica testo',
      'certifyTextSubtitle': 'Scrivi in SIGILLUM. Certifica le tue parole prima di pubblicarle.',
      'verifyTitle': 'Verifica contenuto',
      'verifySubtitle': 'Controlla una foto, un video, un testo pubblicato, un HCVPACK o un HCV-ID.',
      'infoTitle': 'Informazioni e privacy',
      'infoSubtitle': 'Cosa fai tu, cosa fa SIGILLUM e come resta verificabile l’origine.',
      'quickGuideTitle': 'Come si usa SIGILLUM',
      'quickGuideSubtitle':
          'Pochi gesti per te. Certificazione, protezione e verifica dietro le quinte.',
      'quickGuideTooltip': 'Come si usa',
      'trustChain': 'Tu fai pochi gesti. SIGILLUM fa il resto.',
      'controls': 'Cosa protegge SIGILLUM',
      'capture': 'Tu crei',
      'captureText': 'scatta, registra o scrivi',
      'fingerprint': 'SIGILLUM identifica',
      'fingerprintText': 'HCV-ID + impronta',
      'identityStep': 'SIGILLUM collega',
      'identityText': 'Creator + dispositivo',
      'signature': 'SIGILLUM firma',
      'signatureText': 'certificato protetto',
      'registry': 'SIGILLUM registra',
      'registryText': 'Registry + riferimento',
      'checkIntegrity': 'Originale esatto con SHA-256 e confronto delle copie con il riferimento',
      'checkSignature': 'Certificato firmato e collegato alla chiave tecnica del dispositivo',
      'checkWatermark': 'HCV-ID e watermark aiutano a ritrovare il certificato nelle copie',
      'checkRegistry': 'Per foto e video il riferimento protetto viene registrato prima del rilascio all’esterno',
      'checkScreen': 'Controlli multipli sugli indizi di ripresa da schermo',
      'checkSocial':
          'Verifica automatica delle copie e confronto umano con il riferimento SIGILLUM',
      'socialVerifyTitle': 'Verifica ciò che ricevi',
      'socialVerifyStep1':
          'Per foto e video condividi il file con SIGILLUM o selezionalo nell’app. Per un testo pubblicato, copialo e incollalo in Verifica testo.',
      'socialVerifyStep2': 'SIGILLUM recupera l’HCV-ID e il certificato firmato dal Registry.',
      'socialVerifyStep3':
          'Foto e video vengono confrontati con il riferimento protetto; il testo viene confrontato con l’impronta del testo certificato.',
      'socialVerifyStep4':
          'Il risultato distingue originale identico, copia compatibile, derivazione autorizzata, contenuto modificato o verifica non conclusiva.',
      'legalPageTitle': 'Informazioni',
      'legalIntro':
          'SIGILLUM crea l’origine verificabile prima della diffusione. Foto e video nascono dalla Camera SIGILLUM; i testi vengono scritti e certificati nell’app. Il sistema collega contenuto, Creator, dispositivo, HCV-ID, firma e Registry. Compatibilità attuale: iPhone con iOS 16 o successivo; tecnicamente da iPhone 8, 8 Plus e X in avanti.',
      'legalControls': 'Controlli eseguiti',
      'legalData': 'Dati trattati',
      'legalLimits': 'Limiti del servizio',
      'data1':
          'foto, video e HCVPACK certificati restano cifrati nell’area privata dell’app; i file in chiaro sono temporanei',
      'data2':
          'HCV-ID, hash crittografici e certificato firmato collegano l’originale al Registry',
      'data3':
          'metadati tecnici e segnali di acquisizione necessari alla verifica',
      'data4':
          'quando salvi o condividi una foto o un video verso l’esterno, SIGILLUM registra prima un riferimento originale cifrato nella propria infrastruttura privata',
      'limit1':
          'SIGILLUM certifica e verifica la catena tecnica del contenuto; il significato o la verità di ciò che viene rappresentato restano distinti dalla prova tecnica.',
      'limit2':
          'Un avviso di rischio schermo segnala indizi tecnici da valutare; non è da solo una prova automatica di falsificazione.',
      'limit3':
          'La verifica online richiede che il Registry sia raggiungibile.',
      'privacyPolicy': 'Privacy policy',
      'terms': 'Termini del servizio',
      'support': 'Supporto e cancellazione dati',
      'deleteData': 'Cancellazione dati',
      'copied': 'Copiato',
      'technicalIdentityTitle': 'Identità tecnica',
      'technicalIdentityHeading': 'Identità tecnica SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM collega il contenuto alla chiave tecnica del dispositivo e al Creator; quando il KYC è completato, l’account è collegato anche a un’identità verificata documentalmente.',
      'declaredName': 'Nome dichiarato',
      'saveName': 'SALVA NOME',
      'loadingTechnicalIdentity': 'Caricamento identità tecnica...',
      'technicalIdentityLoaded': 'Identità tecnica caricata',
      'enterDeclaredName': 'Inserisci il nome dichiarato',
      'declaredNameSaved': 'Nome dichiarato salvato',
      'technicalCreatorId': 'ID tecnico creator',
      'deviceKeyFingerprint': 'Impronta chiave dispositivo',
      'technicalIdentityFingerprint': 'Impronta identità tecnica',
      'identityAssurance': 'Garanzia identità',
      'legalIdentity': 'Identità legale',
      'verifiedLegalName': 'Nome legale verificato',
      'verifiedLegalCountry': 'Paese documento',
      'startKyc': 'Avvia verifica identità',
      'kycExplanation':
          'La verifica documentale KYC sara gestita da un provider esterno. SIGILLUM salvera solo lo stato minimo della verifica.',
      'kycStarting': 'Avvio verifica identita...',
      'kycLinkReady': 'Link KYC pronto. Aprilo nel browser:',
      'kycConfiguredNoUrl':
          'KYC configurato, ma il server non ha restituito un link.',
      'kycNotAvailable': 'KYC non ancora disponibile',
      'kycOpening': 'Apro la verifica identità...',
      'refreshKyc': 'Aggiorna stato verifica',
      'kycRefreshing': 'Aggiornamento stato verifica...',
      'kycNoSession': 'Nessuna sessione KYC avviata.',
      'kycVerified': 'Identità legale verificata.',
      'kycStatus': 'Stato KYC',
      'kycStatusLabel': 'Stato KYC',
      'kycStatusUnavailable': 'Stato KYC non disponibile',
      'kycRequiresInputHint':
          'Verifica incompleta: premi Avvia verifica identita per riprendere la stessa sessione Stripe.',
      'privacy': 'Privacy',
      'technicalProof': 'Prova tecnica',
      'notGeneratedYet': 'Non ancora generato',
      'verifyContentHeading': 'Verifica contenuto',
      'supportedFiles': 'Supportati:\n.hcvpack, .hcv, foto, video, testo, PDF',
      'selectFile': 'SELEZIONA FILE',
      'selectFileToVerify': 'Seleziona un file da verificare',
      'noFileSelected': 'Nessun file selezionato',
      'filePathUnavailable': 'Path file non disponibile',
      'fileSelected': 'File selezionato',
      'importError': 'Errore import',
      'analyzingFile': 'Analisi file...',
      'fileNotFound': 'File non trovato',
      'unknownFormat': 'Formato non riconosciuto',
      'selectHcv': 'SELEZIONA HCV',
      'selectOriginalMedia': 'SELEZIONA MEDIA ORIGINALE',
      'verifyFromRegistry': 'VERIFICA DA REGISTRY',
      'verifyingShort': 'VERIFICA...',
      'selectHcvFile': 'Seleziona file HCV',
      'selectHcvExtension': 'Seleziona un file .hcv',
      'selectHcvFirst': 'Seleziona prima un file HCV',
      'verifying': 'Verifica in corso...',
      'certificateValid': 'Certificato valido',
      'certificateInvalid': 'Certificato non valido',
      'issuer': 'Emittente',
      'hcvpackDetails': 'Dettagli verifica HCVPACK',
      'hcvpackSelect': 'Seleziona file .hcvpack',
      'hcvpackInvalid': 'Certificato HCV non valido',
      'hcvpackIncomplete': 'Certificato HCV incompleto',
      'verificationComplete': 'Verifica completata',
      'identityUnavailable': 'Identità non disponibile',
      'fileType': 'Tipo file',
      'trustLevel': 'Livello fiducia',
      'liveCapture': 'Cattura live',
      'screenReplayRisk': 'Rischio ripresa schermo',
      'syntheticRisk': 'Rischio sintetico',
      'sceneAuthenticity': 'Autenticità scena',
      'aiProofLevel': 'Livello prova AI',
      'audio': 'Audio',
      'videoPlayerTitle': 'Player SIGILLUM',
      'selectVideoPrompt': 'Seleziona un video',
      'loadVideo': 'CARICA VIDEO',
      'loadHcv': 'CARICA HCV',
      'videoLoaded': 'Video caricato',
      'certificateLoaded': 'Certificato caricato',
      'noCertificate': 'Nessun certificato',
      'invalidCertificate': 'Certificato non valido',
      'hcvNotCompatible': 'HCV non compatibile con questo video',
      'videoModified': 'Video modificato',
      'audioTrust': 'Fiducia audio',
      'textWritePrompt': 'Scrivi qui il testo che vuoi rendere verificabile.',
      'enterText': 'Inserisci un testo',
      'creatingTextCertificate': 'Creazione certificato testo...',
      'registryUploadInProgress': 'Caricamento certificato nel Registry...',
      'registryUploadOk': 'Registry OK: {id}',
      'registryQueuedOffline':
          'Registry non disponibile: certificato conservato e accodato per un nuovo invio.',
      'genericError': 'ERRORE',
      'textCertified': 'TESTO ORIGINALE CERTIFICATO',
      'certificateCreatedInvalid': 'Certificato creato ma NON valido',
      'textCertificateTitle': 'Certifica le tue parole',
      'textToCertify': 'Testo da certificare prima della pubblicazione',
      'certifyTextButton': 'CERTIFICA TESTO',
      'creating': 'CREAZIONE...',
      'newText': 'CREA NUOVO TESTO',
      'verifiableTextCreated': 'Il testo originale è ora verificabile',
      'copyHcvId': 'COPIA HCV-ID',
      'copySocialText': 'COPIA TESTO CON HCV-ID',
      'shareTextPost': 'PUBBLICA / CONDIVIDI TESTO',
      'shareTxtCertificate': 'CONDIVIDI TXT + CERTIFICATO HCV',
      'certificate': 'Certificato',
      'cameraTitle': 'Camera SIGILLUM',
      'createdFiles': 'File creati',
      'shareContent': 'CONDIVIDI CONTENUTO',
      'shareOfflinePack': 'CONDIVIDI HCVPACK OFFLINE',
      'photo': 'FOTO',
      'video': 'VIDEO',
      'photoMode': 'MODALITÀ FOTO',
      'videoMode': 'MODALITÀ VIDEO',
      'certificateVerifiedLabel': 'CERTIFICATO VERIFICATO',
      'notVerifiedLabel': 'NON VERIFICATO',
      'hcvIdCopied': 'HCV-ID copiato',
      'socialTextCopied': 'Testo social copiato',
      'verifiedTextShare': 'Testo certificato con SIGILLUM',
      'openResourceFailed': 'Impossibile aprire questa risorsa.',
      'account': 'Account',
      'recording': 'REGISTRAZIONE IN CORSO',
      'cancel': 'ANNULLA',
      'secureOriginalsTitle': 'I tuoi originali SIGILLUM',
      'secureOriginalsSelectTitle': 'Scegli originale protetto',
      'secureOriginalsSelectIntro':
          'Scegli direttamente un originale cifrato creato con SIGILLUM. Non serve cercarlo nella cartella File.',
      'secureOriginalsSelect': 'SELEZIONA',
      'secureOriginalsIntro':
          'Qui trovi foto e video creati e certificati con la Camera SIGILLUM. Restano protetti nell’area privata dell’app; quando vengono rilasciati all’esterno, SIGILLUM registra prima il riferimento originale protetto.',
      'secureOriginalsEmpty':
          'Non ci sono ancora originali protetti su questo dispositivo.',
      'secureOriginalsLoadError': 'Impossibile caricare gli originali protetti',
      'secureOriginalsViewError': 'Impossibile aprire l’originale',
      'secureOriginalsShareTitle': 'Condividi originale SIGILLUM',
      'secureOriginalsShareDisclosure':
          'Prima di rilasciare il contenuto all’esterno, SIGILLUM verifica l’originale e registra il riferimento protetto sul server. Solo dopo apre il menu di condivisione.',
      'secureOriginalsRightsConfirm':
          'Confermo di disporre dei diritti e delle autorizzazioni necessari per pubblicare questo contenuto.',
      'secureOriginalsContinueShare': 'CONTINUA E CONDIVIDI',
      'secureOriginalsPublishingReference':
          'Verifica dell’originale e registrazione del riferimento ufficiale in corso...',
      'secureOriginalsReferenceReady':
          'Riferimento originale registrato. Ora il contenuto può essere condiviso.',
      'secureOriginalsShareText': 'Contenuto certificato SIGILLUM',
      'secureOriginalsShareComplete': 'Condivisione completata o chiusa.',
      'secureOriginalsShareBlocked': 'Condivisione bloccata',
      'secureOriginalsReferencePublished': 'Riferimento originale protetto',
      'secureOriginalsReferencePending':
          'Riferimento originale non ancora registrato',
      'secureOriginalsWithdraw': 'RITIRA COPIA UFFICIALE',
      'secureOriginalsWithdrawTitle': 'Ritira copia ufficiale',
      'secureOriginalsWithdrawBody':
          'Il riferimento ufficiale verrà rimosso dall’archivio tecnico SIGILLUM e non sarà più disponibile nell’app. Il certificato HCV e il record tecnico restano verificabili.',
      'secureOriginalsWithdrawConfirm': 'RITIRA',
      'secureOriginalsWithdrawing': 'Ritiro della copia ufficiale in corso...',
      'secureOriginalsWithdrawn': 'Copia ufficiale ritirata.',
      'secureOriginalsWithdrawError': 'Impossibile ritirare la copia ufficiale',
      'secureOriginalsWithdrawPending':
          'Ritiro registrato. L’eliminazione del riferimento tecnico è ancora in attesa; puoi ritentare da questa schermata.',
      'secureOriginalsView': 'VISUALIZZA ORIGINALE',
      'secureOriginalsShare': 'CONDIVIDI ORIGINALE',
      'secureOriginalsOfficialCopy': 'VISUALIZZA COPIA UFFICIALE',
      'secureOriginalsViewerTitle': 'Originale SIGILLUM',
      'secureOriginalStored':
          'Originale e HCVPACK cifrati nell’area protetta SIGILLUM.',
      'secureOriginalStorageDetail':
          'L’originale non è salvato in Foto né esposto nella cartella File. Aprilo o condividilo da Originali protetti.',
      'secureOriginalsOpen': 'APRI ORIGINALI PROTETTI',
      'secureOriginalsHomeSubtitle':
          'Apri, salva o condividi i tuoi originali certificati.',
      'verifiedOriginalsTitle': 'RIFERIMENTO SIGILLUM',
      'verifiedOriginalsSubtitle':
          'Ritrova l’originale di riferimento registrato prima della diffusione.',
      'verifiedOriginalsAction': 'TROVA RIFERIMENTO SIGILLUM',
      'voPageTitle': 'Riferimento originale SIGILLUM',
      'voIntro':
          'Inserisci l’HCV-ID per trovare il riferimento originale registrato da SIGILLUM prima che il contenuto venisse diffuso.',
      'voFindId': 'TROVA RIFERIMENTO',
      'voSelectProtected': 'SCEGLI DAGLI ORIGINALI PROTETTI',
      'voSelectFile': 'SELEZIONA FILE ESTERNO',
      'voProtectedPickError': 'Impossibile aprire gli originali protetti.',
      'voInvalidId': 'HCV-ID non valido.',
      'voRegistryError':
          'Registry non raggiungibile o risposta non valida. Nessun risultato di verifica.',
      'voCodeWarning':
          'La presenza del codice non dimostra che il file social sia integro: un HCV-ID può essere copiato.',
      'voVerifyCodeCertificate': 'VERIFICA CERTIFICATO',
      'voAvailable':
          'Riferimento originale disponibile. È il contenuto registrato da SIGILLUM prima del rilascio all’esterno.',
      'voWatch': 'APRI RIFERIMENTO ORIGINALE',
      'voLinkGated':
          'Il riferimento originale non è esposto con un link pubblico permanente. Il certificato resta verificabile gratuitamente; l’apertura del riferimento avviene dentro SIGILLUM secondo le condizioni di accesso previste.',
      'voNotAvailable':
          'Riferimento originale non disponibile. Il certificato HCV può comunque essere verificato.',
      'voSubscriptionRequired':
          'La verifica del certificato resta gratuita. Per visualizzare la copia ufficiale tramite SIGILLUM serve un abbonamento attivo.',
      'voAuthRequired':
          'Accedi con un account SIGILLUM abbonato per visualizzare la copia ufficiale.',
      'voOpenError': 'Impossibile aprire la copia ufficiale.',
      'voFilePickError': 'Impossibile aprire il file selezionato.',
    },
    'en': {
      'identity': 'Identity',
      'accountTitle': 'ACCOUNT',
      'accountSubtitle': 'Profile, identity, KYC, security and data.',
      'creatorEntitlementUnavailable':
          'Unable to verify the Creator subscription. Try again when a connection is available.',
      'headline': 'You create. SIGILLUM protects the origin.',
      'subtitle':
          'Capture, record or write. SIGILLUM creates an HCV-ID and signed certificate, links the content to the Creator and device, and keeps its origin verifiable over time. For photos and videos, the protected reference is registered before the file is released outside the app.',
      'certifyMediaTitle': 'Create and certify a photo or video',
      'certifyMediaSubtitle':
          'Capture or record. SIGILLUM certifies and protects the original.',
      'certifyTextTitle': 'Create and Certify Text',
      'certifyTextSubtitle': 'Write in SIGILLUM. Certify your words before publishing them.',
      'verifyTitle': 'Verify content',
      'verifySubtitle': 'Check a photo, video, published text, HCVPACK or HCV-ID.',
      'infoTitle': 'Information and privacy',
      'infoSubtitle': 'What you do, what SIGILLUM does, and how the origin stays verifiable.',
      'quickGuideTitle': 'How to use SIGILLUM',
      'quickGuideSubtitle':
          'A few actions for you. Certification, protection and verification behind the scenes.',
      'quickGuideTooltip': 'How to use',
      'trustChain': 'You do a few things. SIGILLUM does the rest.',
      'controls': 'What SIGILLUM protects',
      'capture': 'You create',
      'captureText': 'capture, record or write',
      'fingerprint': 'SIGILLUM identifies',
      'fingerprintText': 'HCV-ID + fingerprint',
      'identityStep': 'SIGILLUM links',
      'identityText': 'Creator + device',
      'signature': 'SIGILLUM signs',
      'signatureText': 'protected certificate',
      'registry': 'SIGILLUM registers',
      'registryText': 'Registry + reference',
      'checkIntegrity': 'Exact-original SHA-256 check and copy comparison against the reference',
      'checkSignature': 'Signed certificate linked to the device technical key',
      'checkWatermark': 'HCV-ID and watermark help recover the certificate from copies',
      'checkRegistry': 'For photos and videos, the protected reference is registered before external release',
      'checkScreen': 'Multiple checks for signs of screen recapture',
      'checkSocial':
          'Automatic copy verification plus human comparison with the SIGILLUM reference',
      'socialVerifyTitle': 'Verify what you receive',
      'socialVerifyStep1':
          'For photos and videos, share the file to SIGILLUM or select it in the app. For published text, copy it and paste it into Text verification.',
      'socialVerifyStep2': 'SIGILLUM retrieves the HCV-ID and signed certificate from the Registry.',
      'socialVerifyStep3':
          'Photos and videos are compared with the protected reference; text is compared with the certified text fingerprint.',
      'socialVerifyStep4':
          'The result distinguishes an identical original, compatible copy, authorized derivation, modified content or an inconclusive verification.',
      'legalPageTitle': 'Information',
      'legalIntro':
          'SIGILLUM creates a verifiable origin before distribution. Photos and videos are created with the SIGILLUM Camera; text is written and certified in the app. The system links content, Creator, device, HCV-ID, signature and Registry. Current compatibility: iPhone with iOS 16 or later; technically iPhone 8, 8 Plus and X or later.',
      'legalControls': 'Checks performed',
      'legalData': 'Data processed',
      'legalLimits': 'Service limits',
      'data1':
          'certified photos, videos and HCVPACK files remain encrypted in the app’s private area; clear files are temporary',
      'data2':
          'HCV-ID, cryptographic hashes and the signed certificate bind the original to the Registry',
      'data3':
          'technical metadata and capture signals required for verification',
      'data4':
          'when you save or share a photo or video outside the app, SIGILLUM first registers an encrypted original reference in its private infrastructure',
      'limit1':
          'SIGILLUM certifies and verifies the technical chain of the content; the meaning or truth of what is depicted remains separate from the technical evidence.',
      'limit2':
          'A screen-risk warning reports technical signals that deserve attention; by itself it is not automatic proof of falsification.',
      'limit3': 'Online verification requires the Registry to be reachable.',
      'privacyPolicy': 'Privacy policy',
      'terms': 'Terms of service',
      'support': 'Support and data deletion',
      'deleteData': 'Data deletion',
      'copied': 'Copied',
      'technicalIdentityTitle': 'Technical identity',
      'technicalIdentityHeading': 'SIGILLUM technical identity',
      'technicalIdentityBody':
          'SIGILLUM links content to the device technical key and the Creator; when KYC is completed, the account is also linked to a document-verified identity.',
      'declaredName': 'Declared name',
      'saveName': 'SAVE NAME',
      'loadingTechnicalIdentity': 'Loading technical identity...',
      'technicalIdentityLoaded': 'Technical identity loaded',
      'enterDeclaredName': 'Enter the declared name',
      'declaredNameSaved': 'Declared name saved',
      'technicalCreatorId': 'Technical creator ID',
      'deviceKeyFingerprint': 'Device key fingerprint',
      'technicalIdentityFingerprint': 'Technical identity fingerprint',
      'identityAssurance': 'Identity assurance',
      'legalIdentity': 'Legal identity',
      'verifiedLegalName': 'Verified legal name',
      'verifiedLegalCountry': 'Document country',
      'startKyc': 'Start identity verification',
      'kycExplanation':
          'Document KYC will be handled by an external provider. SIGILLUM will store only the minimum verification status.',
      'kycStarting': 'Starting identity verification...',
      'kycLinkReady': 'KYC link ready. Open it in your browser:',
      'kycConfiguredNoUrl':
          'KYC is configured, but the server did not return a link.',
      'kycNotAvailable': 'KYC not available yet',
      'kycOpening': 'Opening identity verification...',
      'refreshKyc': 'Refresh verification status',
      'kycRefreshing': 'Refreshing verification status...',
      'kycNoSession': 'No KYC session started.',
      'kycVerified': 'Legal identity verified.',
      'kycStatus': 'KYC status',
      'kycStatusLabel': 'KYC status',
      'kycStatusUnavailable': 'KYC status unavailable',
      'kycRequiresInputHint':
          'Verification incomplete: tap Start identity verification to resume the same Stripe session.',
      'privacy': 'Privacy',
      'technicalProof': 'Technical proof',
      'notGeneratedYet': 'Not generated yet',
      'verifyContentHeading': 'Verify content',
      'supportedFiles': 'Supported:\n.hcvpack, .hcv, photos, videos, text, PDF',
      'selectFile': 'SELECT FILE',
      'selectFileToVerify': 'Select a file to verify',
      'noFileSelected': 'No file selected',
      'filePathUnavailable': 'File path unavailable',
      'fileSelected': 'Selected file',
      'importError': 'Import error',
      'analyzingFile': 'Analyzing file...',
      'fileNotFound': 'File not found',
      'unknownFormat': 'Unknown format',
      'selectHcv': 'SELECT HCV',
      'selectOriginalMedia': 'SELECT ORIGINAL MEDIA',
      'verifyFromRegistry': 'VERIFY FROM REGISTRY',
      'verifyingShort': 'VERIFYING...',
      'selectHcvFile': 'Select HCV file',
      'selectHcvExtension': 'Select a .hcv file',
      'selectHcvFirst': 'Select an HCV file first',
      'verifying': 'Verifying...',
      'certificateValid': 'Certificate valid',
      'certificateInvalid': 'Certificate invalid',
      'issuer': 'Issuer',
      'hcvpackDetails': 'HCVPACK verification details',
      'hcvpackSelect': 'Select .hcvpack file',
      'hcvpackInvalid': 'Invalid HCV certificate',
      'hcvpackIncomplete': 'Incomplete HCV certificate',
      'verificationComplete': 'Verification complete',
      'identityUnavailable': 'Identity not available',
      'fileType': 'File type',
      'trustLevel': 'Trust level',
      'liveCapture': 'Live capture',
      'screenReplayRisk': 'Screen replay risk',
      'syntheticRisk': 'Synthetic risk',
      'sceneAuthenticity': 'Scene authenticity',
      'aiProofLevel': 'AI proof level',
      'audio': 'Audio',
      'videoPlayerTitle': 'SIGILLUM Player',
      'selectVideoPrompt': 'Select a video',
      'loadVideo': 'LOAD VIDEO',
      'loadHcv': 'LOAD HCV',
      'videoLoaded': 'Video loaded',
      'certificateLoaded': 'Certificate loaded',
      'noCertificate': 'No certificate selected',
      'invalidCertificate': 'Invalid certificate',
      'hcvNotCompatible': 'HCV is not compatible with this video',
      'videoModified': 'Video has been modified',
      'audioTrust': 'Audio trust',
      'textWritePrompt': 'Write the text you want to make verifiable.',
      'enterText': 'Enter text',
      'creatingTextCertificate': 'Creating text certificate...',
      'registryUploadInProgress': 'Uploading certificate to the Registry...',
      'registryUploadOk': 'Registry OK: {id}',
      'registryQueuedOffline':
          'Registry unavailable: the certificate was kept and queued for retry.',
      'genericError': 'ERROR',
      'textCertified': 'CERTIFIED ORIGINAL TEXT',
      'certificateCreatedInvalid': 'Certificate created but NOT valid',
      'textCertificateTitle': 'Certify your words',
      'textToCertify': 'Text to certify before publication',
      'certifyTextButton': 'CERTIFY TEXT',
      'creating': 'CREATING...',
      'newText': 'CREATE NEW TEXT',
      'verifiableTextCreated': 'The original text is now verifiable',
      'copyHcvId': 'COPY HCV-ID',
      'copySocialText': 'COPY TEXT WITH HCV-ID',
      'shareTextPost': 'PUBLISH / SHARE TEXT',
      'shareTxtCertificate': 'SHARE TXT + HCV CERTIFICATE',
      'certificate': 'Certificate',
      'cameraTitle': 'SIGILLUM Camera',
      'createdFiles': 'Created files',
      'shareContent': 'SHARE CONTENT',
      'shareOfflinePack': 'SHARE OFFLINE HCVPACK',
      'photo': 'PHOTO',
      'video': 'VIDEO',
      'photoMode': 'PHOTO MODE',
      'videoMode': 'VIDEO MODE',
      'certificateVerifiedLabel': 'CERTIFICATE VERIFIED',
      'notVerifiedLabel': 'NOT VERIFIED',
      'hcvIdCopied': 'HCV-ID copied',
      'socialTextCopied': 'Social text copied',
      'verifiedTextShare': 'Text certified with SIGILLUM',
      'openResourceFailed': 'Unable to open this resource.',
      'account': 'Account',
      'recording': 'RECORDING',
      'cancel': 'CANCEL',
      'secureOriginalsTitle': 'Your SIGILLUM originals',
      'secureOriginalsSelectTitle': 'Choose protected original',
      'secureOriginalsSelectIntro':
          'Choose an encrypted original created with SIGILLUM directly. You do not need to find it in Files.',
      'secureOriginalsSelect': 'SELECT',
      'secureOriginalsIntro':
          'Here are the photos and videos created and certified with the SIGILLUM Camera. They remain protected in the app; before they are released outside, SIGILLUM registers the protected original reference.',
      'secureOriginalsEmpty':
          'There are no protected originals on this device yet.',
      'secureOriginalsLoadError': 'Unable to load protected originals',
      'secureOriginalsViewError': 'Unable to open the original',
      'secureOriginalsShareTitle': 'Share SIGILLUM original',
      'secureOriginalsShareDisclosure':
          'Before releasing the content outside the app, SIGILLUM verifies the original and registers the protected server reference. Only then does it open the share sheet.',
      'secureOriginalsRightsConfirm':
          'I confirm that I have the rights and permissions required to publish this content.',
      'secureOriginalsContinueShare': 'CONTINUE AND SHARE',
      'secureOriginalsPublishingReference':
          'Verifying the original and registering the official reference...',
      'secureOriginalsReferenceReady':
          'Original reference registered. The content can now be shared.',
      'secureOriginalsShareText': 'SIGILLUM certified content',
      'secureOriginalsShareComplete': 'Sharing completed or closed.',
      'secureOriginalsShareBlocked': 'Sharing blocked',
      'secureOriginalsReferencePublished': 'Protected original reference',
      'secureOriginalsReferencePending': 'Original reference not yet registered',
      'secureOriginalsWithdraw': 'WITHDRAW OFFICIAL COPY',
      'secureOriginalsWithdrawTitle': 'Withdraw official copy',
      'secureOriginalsWithdrawBody':
          'The official reference will be removed from SIGILLUM technical storage and will no longer be available through Verified Originals. The HCV certificate and technical record remain verifiable.',
      'secureOriginalsWithdrawConfirm': 'WITHDRAW',
      'secureOriginalsWithdrawing': 'Withdrawing the official copy...',
      'secureOriginalsWithdrawn': 'Official copy withdrawn.',
      'secureOriginalsWithdrawError': 'Unable to withdraw the official copy',
      'secureOriginalsWithdrawPending':
          'Withdrawal recorded. Removal of the technical reference is still pending; you can retry from this screen.',
      'secureOriginalsView': 'VIEW ORIGINAL',
      'secureOriginalsShare': 'SHARE ORIGINAL',
      'secureOriginalsOfficialCopy': 'VIEW OFFICIAL COPY',
      'secureOriginalsViewerTitle': 'SIGILLUM original',
      'secureOriginalStored':
          'Original and HCVPACK encrypted in the protected SIGILLUM area.',
      'secureOriginalStorageDetail':
          'The original is not saved to Photos or exposed in the Files folder. Open or share it from Protected originals.',
      'secureOriginalsOpen': 'OPEN PROTECTED ORIGINALS',
      'secureOriginalsHomeSubtitle': 'Open, save or share your certified originals.',
      'verifiedOriginalsTitle': 'SIGILLUM REFERENCE',
      'verifiedOriginalsSubtitle':
          'Find the original reference registered before distribution.',
      'verifiedOriginalsAction': 'FIND SIGILLUM REFERENCE',
      'voPageTitle': 'SIGILLUM original reference',
      'voIntro':
          'Enter the HCV-ID to find the original reference SIGILLUM registered before the content was distributed.',
      'voFindId': 'FIND REFERENCE',
      'voSelectProtected': 'CHOOSE FROM PROTECTED ORIGINALS',
      'voSelectFile': 'SELECT EXTERNAL FILE',
      'voProtectedPickError': 'Unable to open protected originals.',
      'voInvalidId': 'Invalid HCV-ID.',
      'voRegistryError':
          'Registry unavailable or invalid response. No verification result.',
      'voCodeWarning':
          'The presence of a code does not prove that a social file is intact: an HCV-ID can be copied.',
      'voVerifyCodeCertificate': 'VERIFY CERTIFICATE',
      'voAvailable':
          'Original reference available. This is the content SIGILLUM registered before external release.',
      'voWatch': 'OPEN ORIGINAL REFERENCE',
      'voLinkGated':
          'The original reference is not exposed through a permanent public link. Certificate verification remains free; the reference opens inside SIGILLUM under the applicable access conditions.',
      'voNotAvailable':
          'Original reference unavailable. The HCV certificate can still be verified.',
      'voSubscriptionRequired':
          'Certificate verification remains free. Viewing the official copy through SIGILLUM requires an active subscription.',
      'voAuthRequired':
          'Sign in with a subscribed SIGILLUM account to view the official copy.',
      'voOpenError': 'Unable to open the official copy.',
      'voFilePickError': 'Unable to open the selected file.',
    },
    'es': {
      'identity': 'Identidad',
      'accountTitle': 'CUENTA',
      'accountSubtitle': 'Perfil, identidad, KYC, seguridad y datos.',
      'creatorEntitlementUnavailable':
          'No se puede verificar la suscripción Creator. Inténtalo de nuevo cuando haya conexión.',
      'headline': 'Tú creas. SIGILLUM protege el origen.',
      'subtitle':
          'Captura, graba o escribe. SIGILLUM crea un HCV-ID y un certificado firmado, vincula el contenido con el Creator y el dispositivo y mantiene verificable su origen. Para fotos y vídeos, registra la referencia protegida antes de liberar el archivo fuera de la app.',
      'certifyMediaTitle': 'Crear y certificar una foto o un vídeo',
      'certifyMediaSubtitle': 'Captura o graba. SIGILLUM certifica y protege el original.',
      'certifyTextTitle': 'Crear y certificar texto',
      'certifyTextSubtitle': 'Escribe en SIGILLUM. Certifica tus palabras antes de publicarlas.',
      'verifyTitle': 'Verificar contenido',
      'verifySubtitle': 'Comprueba una foto, vídeo, texto publicado, HCVPACK o HCV-ID.',
      'infoTitle': 'Informacion y privacidad',
      'infoSubtitle': 'Qué haces tú, qué hace SIGILLUM y cómo el origen sigue siendo verificable.',
      'quickGuideTitle': 'Cómo usar SIGILLUM',
      'quickGuideSubtitle':
          'Pocos pasos para ti. Certificación, protección y verificación en segundo plano.',
      'quickGuideTooltip': 'Cómo se usa',
      'trustChain': 'Tú haces pocos pasos. SIGILLUM hace el resto.',
      'controls': 'Qué protege SIGILLUM',
      'capture': 'Tú creas',
      'captureText': 'captura, graba o escribe',
      'fingerprint': 'SIGILLUM identifica',
      'fingerprintText': 'HCV-ID + huella',
      'identityStep': 'SIGILLUM vincula',
      'identityText': 'Creator + dispositivo',
      'signature': 'SIGILLUM firma',
      'signatureText': 'certificado protegido',
      'registry': 'SIGILLUM registra',
      'registryText': 'Registry + referencia',
      'checkIntegrity': 'Comprobación SHA-256 del original exacto y comparación de copias con la referencia',
      'checkSignature': 'Certificado firmado y vinculado a la clave técnica del dispositivo',
      'checkWatermark': 'HCV-ID y watermark ayudan a recuperar el certificado desde las copias',
      'checkRegistry': 'Para fotos y vídeos, la referencia protegida se registra antes de liberarlos al exterior',
      'checkScreen': 'Múltiples controles de indicios de recaptura de pantalla',
      'checkSocial':
          'Verificación automática de copias y comparación humana con la referencia SIGILLUM',
      'socialVerifyTitle': 'Verifica lo que recibes',
      'socialVerifyStep1':
          'Para fotos y vídeos, comparte el archivo con SIGILLUM o selecciónalo en la app. Para un texto publicado, cópialo y pégalo en Verificación de texto.',
      'socialVerifyStep2': 'SIGILLUM recupera el HCV-ID y el certificado firmado desde el Registry.',
      'socialVerifyStep3':
          'Las fotos y los vídeos se comparan con la referencia protegida; el texto se compara con la huella del texto certificado.',
      'socialVerifyStep4':
          'El resultado distingue original idéntico, copia compatible, derivación autorizada, contenido modificado o verificación no concluyente.',
      'legalPageTitle': 'Informacion',
      'legalIntro':
          'SIGILLUM crea un origen verificable antes de la difusión. Las fotos y los vídeos se crean con la Cámara SIGILLUM; los textos se escriben y certifican en la app. El sistema vincula contenido, Creator, dispositivo, HCV-ID, firma y Registry. Compatibilidad actual: iPhone con iOS 16 o posterior; técnicamente desde iPhone 8, 8 Plus y X en adelante.',
      'legalControls': 'Controles realizados',
      'legalData': 'Datos tratados',
      'legalLimits': 'Limites del servicio',
      'data1':
          'las fotos, vídeos y HCVPACK certificados permanecen cifrados en el área privada de la app; los archivos en claro son temporales',
      'data2':
          'HCV-ID, hashes criptográficos y certificado firmado vinculan el original al Registry',
      'data3':
          'metadatos técnicos y señales de captura necesarios para la verificación',
      'data4':
          'cuando guardas o compartes una foto o un vídeo fuera de la app, SIGILLUM registra primero una referencia original cifrada en su infraestructura privada',
      'limit1':
          'SIGILLUM certifica y verifica la cadena técnica del contenido; el significado o la verdad de lo representado permanece separado de la evidencia técnica.',
      'limit2':
          'Una advertencia de riesgo de pantalla informa de señales técnicas que merecen atención; por sí sola no es una prueba automática de falsificación.',
      'limit3':
          'La verificacion online requiere que el Registry este accesible.',
      'privacyPolicy': 'Politica de privacidad',
      'terms': 'Terminos del servicio',
      'support': 'Soporte y eliminacion de datos',
      'deleteData': 'Eliminacion de datos',
      'copied': 'Copiado',
      'technicalIdentityTitle': 'Identidad tecnica',
      'technicalIdentityHeading': 'Identidad tecnica SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM vincula el contenido a la clave técnica del dispositivo y al Creator; cuando se completa el KYC, la cuenta queda vinculada también a una identidad verificada documentalmente.',
      'declaredName': 'Nombre declarado',
      'saveName': 'GUARDAR NOMBRE',
      'loadingTechnicalIdentity': 'Cargando identidad tecnica...',
      'technicalIdentityLoaded': 'Identidad tecnica cargada',
      'enterDeclaredName': 'Introduce el nombre declarado',
      'declaredNameSaved': 'Nombre declarado guardado',
      'technicalCreatorId': 'ID tecnico del creador',
      'deviceKeyFingerprint': 'Huella de clave del dispositivo',
      'technicalIdentityFingerprint': 'Huella de identidad tecnica',
      'identityAssurance': 'Garantia de identidad',
      'legalIdentity': 'Identidad legal',
      'verifiedLegalName': 'Nombre legal verificado',
      'verifiedLegalCountry': 'Pais del documento',
      'startKyc': 'Iniciar verificacion de identidad',
      'kycExplanation':
          'El KYC documental sera gestionado por un proveedor externo. SIGILLUM guardara solo el estado minimo de verificacion.',
      'kycStarting': 'Iniciando verificacion de identidad...',
      'kycLinkReady': 'Link KYC listo. Abrelo en el navegador:',
      'kycConfiguredNoUrl':
          'KYC configurado, pero el servidor no devolvio un link.',
      'kycNotAvailable': 'KYC aun no disponible',
      'kycOpening': 'Abriendo verificacion de identidad...',
      'refreshKyc': 'Actualizar estado de verificacion',
      'kycRefreshing': 'Actualizando estado de verificacion...',
      'kycNoSession': 'No hay ninguna sesion KYC iniciada.',
      'kycVerified': 'Identidad legal verificada.',
      'kycStatus': 'Estado KYC',
      'kycStatusLabel': 'Estado KYC',
      'kycStatusUnavailable': 'Estado KYC no disponible',
      'kycRequiresInputHint':
          'Verificacion incompleta: toca Iniciar verificacion de identidad para reanudar la misma sesion de Stripe.',
      'privacy': 'Privacidad',
      'technicalProof': 'Prueba tecnica',
      'notGeneratedYet': 'Aun no generado',
      'verifyContentHeading': 'Verificar contenido',
      'supportedFiles':
          'Soportados:\n.hcvpack, .hcv, fotos, videos, texto, PDF',
      'selectFile': 'SELECCIONAR ARCHIVO',
      'selectFileToVerify': 'Selecciona un archivo para verificar',
      'noFileSelected': 'Ningun archivo seleccionado',
      'filePathUnavailable': 'Ruta del archivo no disponible',
      'fileSelected': 'Archivo seleccionado',
      'importError': 'Error de importacion',
      'analyzingFile': 'Analizando archivo...',
      'fileNotFound': 'Archivo no encontrado',
      'unknownFormat': 'Formato no reconocido',
      'selectHcv': 'SELECCIONAR HCV',
      'selectOriginalMedia': 'SELECCIONAR MEDIA ORIGINAL',
      'verifyFromRegistry': 'VERIFICAR EN REGISTRY',
      'verifyingShort': 'VERIFICANDO...',
      'selectHcvFile': 'Selecciona archivo HCV',
      'selectHcvExtension': 'Selecciona un archivo .hcv',
      'selectHcvFirst': 'Selecciona primero un archivo HCV',
      'verifying': 'Verificando...',
      'certificateValid': 'Certificado valido',
      'certificateInvalid': 'Certificado no valido',
      'issuer': 'Emisor',
      'hcvpackDetails': 'Detalles de verificacion HCVPACK',
      'hcvpackSelect': 'Selecciona archivo .hcvpack',
      'hcvpackInvalid': 'Certificado HCV no valido',
      'hcvpackIncomplete': 'Certificado HCV incompleto',
      'verificationComplete': 'Verificacion completada',
      'identityUnavailable': 'Identidad no disponible',
      'fileType': 'Tipo de archivo',
      'trustLevel': 'Nivel de confianza',
      'liveCapture': 'Captura en vivo',
      'screenReplayRisk': 'Riesgo de pantalla',
      'syntheticRisk': 'Riesgo sintetico',
      'sceneAuthenticity': 'Autenticidad de escena',
      'aiProofLevel': 'Nivel de prueba IA',
      'audio': 'Audio',
      'videoPlayerTitle': 'Reproductor SIGILLUM',
      'selectVideoPrompt': 'Selecciona un vídeo',
      'loadVideo': 'CARGAR VÍDEO',
      'loadHcv': 'CARGAR HCV',
      'videoLoaded': 'Vídeo cargado',
      'certificateLoaded': 'Certificado cargado',
      'noCertificate': 'No se ha seleccionado un certificado',
      'invalidCertificate': 'Certificado no válido',
      'hcvNotCompatible': 'El HCV no es compatible con este vídeo',
      'videoModified': 'El vídeo ha sido modificado',
      'audioTrust': 'Confianza audio',
      'textWritePrompt': 'Escribe aquí el texto que quieres hacer verificable.',
      'enterText': 'Introduce un texto',
      'creatingTextCertificate': 'Creando certificado de texto...',
      'registryUploadInProgress': 'Subiendo el certificado al Registry...',
      'registryUploadOk': 'Registry OK: {id}',
      'registryQueuedOffline':
          'Registry no disponible: el certificado se conservó y quedó en cola para reintentar.',
      'genericError': 'ERROR',
      'textCertified': 'TEXTO ORIGINAL CERTIFICADO',
      'certificateCreatedInvalid': 'Certificado creado pero NO valido',
      'textCertificateTitle': 'Certifica tus palabras',
      'textToCertify': 'Texto que se certificará antes de publicarlo',
      'certifyTextButton': 'CERTIFICAR TEXTO',
      'creating': 'CREANDO...',
      'newText': 'CREAR NUEVO TEXTO',
      'verifiableTextCreated': 'El texto original ya es verificable',
      'copyHcvId': 'COPIAR HCV-ID',
      'copySocialText': 'COPIAR TEXTO CON HCV-ID',
      'shareTextPost': 'PUBLICAR / COMPARTIR TEXTO',
      'shareTxtCertificate': 'COMPARTIR TXT + CERTIFICADO HCV',
      'certificate': 'Certificado',
      'cameraTitle': 'Camara SIGILLUM',
      'createdFiles': 'Archivos creados',
      'shareContent': 'COMPARTIR CONTENIDO',
      'shareOfflinePack': 'COMPARTIR HCVPACK OFFLINE',
      'photo': 'FOTO',
      'video': 'VIDEO',
      'photoMode': 'MODO FOTO',
      'videoMode': 'MODO VIDEO',
      'certificateVerifiedLabel': 'CERTIFICADO VERIFICADO',
      'notVerifiedLabel': 'NO VERIFICADO',
      'hcvIdCopied': 'HCV-ID copiado',
      'socialTextCopied': 'Texto social copiado',
      'verifiedTextShare': 'Texto certificado con SIGILLUM',
      'openResourceFailed': 'No se puede abrir este recurso.',
      'account': 'Cuenta',
      'recording': 'GRABANDO',
      'cancel': 'CANCELAR',
      'secureOriginalsTitle': 'Tus originales SIGILLUM',
      'secureOriginalsSelectTitle': 'Elegir original protegido',
      'secureOriginalsSelectIntro':
          'Elige directamente un original cifrado creado con SIGILLUM. No necesitas buscarlo en Archivos.',
      'secureOriginalsSelect': 'SELECCIONAR',
      'secureOriginalsIntro':
          'Aquí están las fotos y los vídeos creados y certificados con la Cámara SIGILLUM. Permanecen protegidos en la app; antes de salir al exterior, SIGILLUM registra la referencia original protegida.',
      'secureOriginalsEmpty':
          'Todavía no hay originales protegidos en este dispositivo.',
      'secureOriginalsLoadError':
          'No se pueden cargar los originales protegidos',
      'secureOriginalsViewError': 'No se puede abrir el original',
      'secureOriginalsShareTitle': 'Compartir original SIGILLUM',
      'secureOriginalsShareDisclosure':
          'Antes de liberar el contenido fuera de la app, SIGILLUM verifica el original y registra la referencia protegida en el servidor. Solo después abre el menú Compartir.',
      'secureOriginalsRightsConfirm':
          'Confirmo que dispongo de los derechos y autorizaciones necesarios para publicar este contenido.',
      'secureOriginalsContinueShare': 'CONTINUAR Y COMPARTIR',
      'secureOriginalsPublishingReference':
          'Verificando el original y registrando la referencia oficial...',
      'secureOriginalsReferenceReady':
          'Referencia original registrada. El contenido ya puede compartirse.',
      'secureOriginalsShareText': 'Contenido certificado SIGILLUM',
      'secureOriginalsShareComplete': 'Compartición completada o cerrada.',
      'secureOriginalsShareBlocked': 'Compartición bloqueada',
      'secureOriginalsReferencePublished': 'Referencia original protegida',
      'secureOriginalsReferencePending': 'Referencia original aún no registrada',
      'secureOriginalsWithdraw': 'RETIRAR COPIA OFICIAL',
      'secureOriginalsWithdrawTitle': 'Retirar copia oficial',
      'secureOriginalsWithdrawBody':
          'La referencia oficial se eliminará del almacenamiento técnico de SIGILLUM y dejará de estar disponible en la app. El certificado HCV y el registro técnico seguirán siendo verificables.',
      'secureOriginalsWithdrawConfirm': 'RETIRAR',
      'secureOriginalsWithdrawing': 'Retirando la copia oficial...',
      'secureOriginalsWithdrawn': 'Copia oficial retirada.',
      'secureOriginalsWithdrawError': 'No se puede retirar la copia oficial',
      'secureOriginalsWithdrawPending':
          'Retirada registrada. La eliminación de la referencia técnica sigue pendiente; puedes volver a intentarlo desde esta pantalla.',
      'secureOriginalsView': 'VER ORIGINAL',
      'secureOriginalsShare': 'COMPARTIR ORIGINAL',
      'secureOriginalsOfficialCopy': 'VER COPIA OFICIAL',
      'secureOriginalsViewerTitle': 'Original SIGILLUM',
      'secureOriginalStored':
          'Original y HCVPACK cifrados en el área protegida de SIGILLUM.',
      'secureOriginalStorageDetail':
          'El original no se guarda en Fotos ni se expone en la carpeta Archivos. Ábrelo o compártelo desde Originales protegidos.',
      'secureOriginalsOpen': 'ABRIR ORIGINALES PROTEGIDOS',
      'secureOriginalsHomeSubtitle':
          'Abre, guarda o comparte tus originales certificados.',
      'verifiedOriginalsTitle': 'REFERENCIA SIGILLUM',
      'verifiedOriginalsSubtitle':
          'Encuentra la referencia original registrada antes de la difusión.',
      'verifiedOriginalsAction': 'BUSCAR REFERENCIA SIGILLUM',
      'voPageTitle': 'Referencia original SIGILLUM',
      'voIntro':
          'Introduce el HCV-ID para encontrar la referencia original que SIGILLUM registró antes de la difusión del contenido.',
      'voFindId': 'BUSCAR REFERENCIA',
      'voSelectProtected': 'ELEGIR DE ORIGINALES PROTEGIDOS',
      'voSelectFile': 'SELECCIONAR ARCHIVO EXTERNO',
      'voProtectedPickError': 'No se pueden abrir los originales protegidos.',
      'voInvalidId': 'HCV-ID no válido.',
      'voRegistryError':
          'Registry no disponible o respuesta no válida. No hay resultado de verificación.',
      'voCodeWarning':
          'La presencia del código no demuestra que un archivo de una red social esté íntegro: un HCV-ID puede copiarse.',
      'voVerifyCodeCertificate': 'VERIFICAR CERTIFICADO',
      'voAvailable':
          'Referencia original disponible. Es el contenido que SIGILLUM registró antes de liberarlo al exterior.',
      'voWatch': 'ABRIR REFERENCIA ORIGINAL',
      'voLinkGated':
          'La referencia original no se expone mediante un enlace público permanente. La verificación del certificado sigue siendo gratuita; la referencia se abre dentro de SIGILLUM según las condiciones de acceso aplicables.',
      'voNotAvailable':
          'Referencia original no disponible. El certificado HCV puede seguir verificándose.',
      'voSubscriptionRequired':
          'La verificación del certificado sigue siendo gratuita. Para ver la copia oficial mediante SIGILLUM se necesita una suscripción activa.',
      'voAuthRequired':
          'Inicia sesión con una cuenta SIGILLUM suscrita para ver la copia oficial.',
      'voOpenError': 'No se puede abrir la copia oficial.',
      'voFilePickError': 'No se puede abrir el archivo seleccionado.',
    },
    'ru': {
      'identity': 'Идентичность',
      'accountTitle': 'АККАУНТ',
      'accountSubtitle': 'Профиль, личность, KYC, безопасность и данные.',
      'creatorEntitlementUnavailable':
          'Не удалось проверить подписку Creator. Повторите попытку при наличии подключения.',
      'headline': 'Вы создаёте. SIGILLUM защищает источник.',
      'subtitle':
          'Снимайте, записывайте или пишите. SIGILLUM создаёт HCV-ID и подписанный сертификат, связывает контент с Creator и устройством и сохраняет проверяемость его происхождения. Для фото и видео защищённый эталон регистрируется до выдачи файла за пределы приложения.',
      'certifyMediaTitle': 'Создать и сертифицировать фото или видео',
      'certifyMediaSubtitle': 'Снимайте или записывайте. SIGILLUM сертифицирует и защищает оригинал.',
      'certifyTextTitle': 'Создать и сертифицировать текст',
      'certifyTextSubtitle': 'Пишите в SIGILLUM. Сертифицируйте свои слова до публикации.',
      'verifyTitle': 'Проверить контент',
      'verifySubtitle': 'Проверьте фото, видео, опубликованный текст, HCVPACK или HCV-ID.',
      'infoTitle': 'Информация и конфиденциальность',
      'infoSubtitle': 'Что делаете вы, что делает SIGILLUM и как происхождение остаётся проверяемым.',
      'quickGuideTitle': 'Как пользоваться SIGILLUM',
      'quickGuideSubtitle':
          'Несколько действий для вас. Сертификация, защита и проверка выполняются в фоне.',
      'quickGuideTooltip': 'Как пользоваться',
      'trustChain': 'Вы делаете несколько действий. Остальное делает SIGILLUM.',
      'controls': 'Что защищает SIGILLUM',
      'capture': 'Вы создаёте',
      'captureText': 'снимаете, записываете или пишете',
      'fingerprint': 'SIGILLUM идентифицирует',
      'fingerprintText': 'HCV-ID + отпечаток',
      'identityStep': 'SIGILLUM связывает',
      'identityText': 'Creator + устройство',
      'signature': 'SIGILLUM подписывает',
      'signatureText': 'защищённый сертификат',
      'registry': 'SIGILLUM регистрирует',
      'registryText': 'Registry + эталон',
      'checkIntegrity': 'SHA-256 для точного оригинала и сравнение копий с эталоном',
      'checkSignature': 'Подписанный сертификат, связанный с техническим ключом устройства',
      'checkWatermark': 'HCV-ID и watermark помогают найти сертификат по копии',
      'checkRegistry': 'Для фото и видео защищённый эталон регистрируется до выдачи контента наружу',
      'checkScreen': 'Несколько проверок признаков пересъёмки с экрана',
      'checkSocial':
          'Автоматическая проверка копий и визуальное сравнение с эталоном SIGILLUM',
      'socialVerifyTitle': 'Проверяйте то, что получаете',
      'socialVerifyStep1':
          'Для фото и видео отправьте файл в SIGILLUM или выберите его в приложении. Опубликованный текст скопируйте и вставьте в Проверку текста.',
      'socialVerifyStep2': 'SIGILLUM получает HCV-ID и подписанный сертификат из Registry.',
      'socialVerifyStep3':
          'Фото и видео сравниваются с защищённым эталоном; текст — с отпечатком сертифицированного текста.',
      'socialVerifyStep4':
          'Результат различает идентичный оригинал, совместимую копию, разрешённую производную версию, изменённый контент или неоднозначную проверку.',
      'legalPageTitle': 'Информация',
      'legalIntro':
          'SIGILLUM создаёт проверяемое происхождение до распространения. Фото и видео создаются Камерой SIGILLUM; текст пишется и сертифицируется в приложении. Система связывает контент, Creator, устройство, HCV-ID, подпись и Registry. Текущая совместимость: iPhone с iOS 16 или новее; технически iPhone 8, 8 Plus и X или новее.',
      'legalControls': 'Выполняемые проверки',
      'legalData': 'Обрабатываемые данные',
      'legalLimits': 'Ограничения сервиса',
      'data1':
          'сертифицированные фото, видео и HCVPACK остаются зашифрованными в закрытой области приложения; открытые файлы создаются временно',
      'data2':
          'HCV-ID, криптографические хеши и подписанный сертификат связывают оригинал с Registry',
      'data3':
          'технические метаданные и сигналы захвата, необходимые для проверки',
      'data4':
          'когда вы сохраняете или отправляете фото или видео за пределы приложения, SIGILLUM сначала регистрирует зашифрованный оригинальный эталон в своей закрытой инфраструктуре',
      'limit1':
          'SIGILLUM сертифицирует и проверяет техническую цепочку контента; смысл или истинность изображённого остаются отдельными от технического доказательства.',
      'limit2':
          'Предупреждение о риске экрана сообщает о технических сигналах, требующих внимания; само по себе оно не является автоматическим доказательством подделки.',
      'limit3': 'Онлайн-проверка требует доступности Registry.',
      'privacyPolicy': 'Политика конфиденциальности',
      'terms': 'Условия сервиса',
      'support': 'Поддержка и удаление данных',
      'deleteData': 'Удаление данных',
      'copied': 'Скопировано',
      'technicalIdentityTitle': 'Техническая идентичность',
      'technicalIdentityHeading': 'Техническая идентичность SIGILLUM',
      'technicalIdentityBody':
          'SIGILLUM связывает контент с техническим ключом устройства и Creator; после завершения KYC аккаунт также связывается с документально подтверждённой личностью.',
      'declaredName': 'Указанное имя',
      'saveName': 'СОХРАНИТЬ ИМЯ',
      'loadingTechnicalIdentity': 'Загрузка технической идентичности...',
      'technicalIdentityLoaded': 'Техническая идентичность загружена',
      'enterDeclaredName': 'Введите указанное имя',
      'declaredNameSaved': 'Указанное имя сохранено',
      'technicalCreatorId': 'Технический ID автора',
      'deviceKeyFingerprint': 'Отпечаток ключа устройства',
      'technicalIdentityFingerprint': 'Отпечаток технической идентичности',
      'identityAssurance': 'Уровень идентичности',
      'legalIdentity': 'Юридическая идентичность',
      'verifiedLegalName': 'Verified legal name',
      'verifiedLegalCountry': 'Document country',
      'startKyc': 'Начать проверку личности',
      'kycExplanation':
          'Проверка документов KYC будет выполняться внешним провайдером. SIGILLUM сохранит только минимальный статус проверки.',
      'kycStarting': 'Запуск проверки личности...',
      'kycLinkReady': 'Ссылка KYC готова. Откройте ее в браузере:',
      'kycConfiguredNoUrl': 'KYC настроен, но сервер не вернул ссылку.',
      'kycNotAvailable': 'KYC пока недоступен',
      'kycOpening': 'Открываю проверку личности...',
      'refreshKyc': 'Обновить статус проверки',
      'kycRefreshing': 'Обновление статуса проверки...',
      'kycNoSession': 'Сессия KYC не запущена.',
      'kycVerified': 'Юридическая личность подтверждена.',
      'kycStatus': 'Статус KYC',
      'kycStatusLabel': 'Статус KYC',
      'kycStatusUnavailable': 'Статус KYC недоступен',
      'kycRequiresInputHint':
          'Verification incomplete: reopen identity verification to resume the same Stripe session.',
      'privacy': 'Конфиденциальность',
      'technicalProof': 'Техническое доказательство',
      'notGeneratedYet': 'Еще не создано',
      'verifyContentHeading': 'Проверить контент',
      'supportedFiles':
          'Поддерживаются:\n.hcvpack, .hcv, фото, видео, текст, PDF',
      'selectFile': 'ВЫБРАТЬ ФАЙЛ',
      'selectFileToVerify': 'Выберите файл для проверки',
      'noFileSelected': 'Файл не выбран',
      'filePathUnavailable': 'Путь к файлу недоступен',
      'fileSelected': 'Выбранный файл',
      'importError': 'Ошибка импорта',
      'analyzingFile': 'Анализ файла...',
      'fileNotFound': 'Файл не найден',
      'unknownFormat': 'Неизвестный формат',
      'selectHcv': 'ВЫБРАТЬ HCV',
      'selectOriginalMedia': 'ВЫБРАТЬ ОРИГИНАЛ',
      'verifyFromRegistry': 'ПРОВЕРИТЬ В REGISTRY',
      'verifyingShort': 'ПРОВЕРКА...',
      'selectHcvFile': 'Выберите HCV-файл',
      'selectHcvExtension': 'Выберите файл .hcv',
      'selectHcvFirst': 'Сначала выберите HCV-файл',
      'verifying': 'Проверка...',
      'certificateValid': 'Сертификат действителен',
      'certificateInvalid': 'Сертификат недействителен',
      'issuer': 'Эмитент',
      'hcvpackDetails': 'Детали проверки HCVPACK',
      'hcvpackSelect': 'Выберите файл .hcvpack',
      'hcvpackInvalid': 'Недействительный HCV-сертификат',
      'hcvpackIncomplete': 'Неполный HCV-сертификат',
      'verificationComplete': 'Проверка завершена',
      'identityUnavailable': 'Идентичность недоступна',
      'fileType': 'Тип файла',
      'trustLevel': 'Уровень доверия',
      'liveCapture': 'Живая съемка',
      'screenReplayRisk': 'Риск пересъемки экрана',
      'syntheticRisk': 'Синтетический риск',
      'sceneAuthenticity': 'Подлинность сцены',
      'aiProofLevel': 'Уровень AI-доказательства',
      'audio': 'Аудио',
      'videoPlayerTitle': 'Проигрыватель SIGILLUM',
      'selectVideoPrompt': 'Выберите видео',
      'loadVideo': 'ЗАГРУЗИТЬ ВИДЕО',
      'loadHcv': 'ЗАГРУЗИТЬ HCV',
      'videoLoaded': 'Видео загружено',
      'certificateLoaded': 'Сертификат загружен',
      'noCertificate': 'Сертификат не выбран',
      'invalidCertificate': 'Недействительный сертификат',
      'hcvNotCompatible': 'HCV не соответствует этому видео',
      'videoModified': 'Видео было изменено',
      'audioTrust': 'Доверие к аудио',
      'textWritePrompt': 'Напишите текст, который хотите сделать проверяемым.',
      'enterText': 'Введите текст',
      'creatingTextCertificate': 'Создание текстового сертификата...',
      'registryUploadInProgress': 'Загрузка сертификата в Registry...',
      'registryUploadOk': 'Registry OK: {id}',
      'registryQueuedOffline':
          'Registry недоступен: сертификат сохранён и поставлен в очередь на повторную отправку.',
      'genericError': 'ОШИБКА',
      'textCertified': 'ОРИГИНАЛЬНЫЙ ТЕКСТ СЕРТИФИЦИРОВАН',
      'certificateCreatedInvalid': 'Сертификат создан, но НЕ действителен',
      'textCertificateTitle': 'Сертифицируйте свои слова',
      'textToCertify': 'Текст для сертификации до публикации',
      'certifyTextButton': 'СЕРТИФИЦИРОВАТЬ ТЕКСТ',
      'creating': 'СОЗДАНИЕ...',
      'newText': 'СОЗДАТЬ НОВЫЙ ТЕКСТ',
      'verifiableTextCreated': 'Оригинальный текст теперь можно проверить',
      'copyHcvId': 'КОПИРОВАТЬ HCV-ID',
      'copySocialText': 'КОПИРОВАТЬ ТЕКСТ С HCV-ID',
      'shareTextPost': 'ОПУБЛИКОВАТЬ / ОТПРАВИТЬ ТЕКСТ',
      'shareTxtCertificate': 'ПОДЕЛИТЬСЯ TXT + HCV-СЕРТИФИКАТОМ',
      'certificate': 'Сертификат',
      'cameraTitle': 'Камера SIGILLUM',
      'createdFiles': 'Созданные файлы',
      'shareContent': 'ПОДЕЛИТЬСЯ КОНТЕНТОМ',
      'shareOfflinePack': 'ПОДЕЛИТЬСЯ HCVPACK OFFLINE',
      'photo': 'ФОТО',
      'video': 'ВИДЕО',
      'photoMode': 'РЕЖИМ ФОТО',
      'videoMode': 'РЕЖИМ ВИДЕО',
      'certificateVerifiedLabel': 'СЕРТИФИКАТ ПОДТВЕРЖДЁН',
      'notVerifiedLabel': 'НЕ ПОДТВЕРЖДЕНО',
      'hcvIdCopied': 'HCV-ID скопирован',
      'socialTextCopied': 'Текст для публикации скопирован',
      'verifiedTextShare': 'Текст сертифицирован SIGILLUM',
      'openResourceFailed': 'Не удалось открыть этот ресурс.',
      'account': 'Аккаунт',
      'recording': 'ИДЕТ ЗАПИСЬ',
      'cancel': 'ОТМЕНА',
      'secureOriginalsTitle': 'Ваши оригиналы SIGILLUM',
      'secureOriginalsSelectTitle': 'Выберите защищённый оригинал',
      'secureOriginalsSelectIntro':
          'Выберите зашифрованный оригинал, созданный в SIGILLUM, прямо здесь. Искать его в Files не требуется.',
      'secureOriginalsSelect': 'ВЫБРАТЬ',
      'secureOriginalsIntro':
          'Здесь находятся фото и видео, созданные и сертифицированные Камерой SIGILLUM. Они защищены в приложении; перед выдачей наружу SIGILLUM регистрирует защищённый оригинальный эталон.',
      'secureOriginalsEmpty':
          'На этом устройстве пока нет защищённых оригиналов.',
      'secureOriginalsLoadError': 'Не удалось загрузить защищённые оригиналы',
      'secureOriginalsViewError': 'Не удалось открыть оригинал',
      'secureOriginalsShareTitle': 'Поделиться оригиналом SIGILLUM',
      'secureOriginalsShareDisclosure':
          'Перед выдачей контента за пределы приложения SIGILLUM проверяет оригинал и регистрирует защищённый серверный эталон. Только после этого открывается меню отправки.',
      'secureOriginalsRightsConfirm':
          'Я подтверждаю наличие необходимых прав и разрешений на публикацию этого контента.',
      'secureOriginalsContinueShare': 'ПРОДОЛЖИТЬ И ПОДЕЛИТЬСЯ',
      'secureOriginalsPublishingReference':
          'Проверка оригинала и регистрация официального эталона...',
      'secureOriginalsReferenceReady':
          'Оригинальный эталон зарегистрирован. Теперь контент можно отправить.',
      'secureOriginalsShareText': 'Сертифицированный контент SIGILLUM',
      'secureOriginalsShareComplete': 'Отправка завершена или закрыта.',
      'secureOriginalsShareBlocked': 'Отправка заблокирована',
      'secureOriginalsReferencePublished': 'Защищённый оригинальный эталон',
      'secureOriginalsReferencePending': 'Оригинальный эталон ещё не зарегистрирован',
      'secureOriginalsWithdraw': 'ОТОЗВАТЬ ОФИЦИАЛЬНУЮ КОПИЮ',
      'secureOriginalsWithdrawTitle': 'Отозвать официальную копию',
      'secureOriginalsWithdrawBody':
          'Официальный эталон будет удалён из технического хранилища SIGILLUM и перестанет быть доступен в приложении. HCV-сертификат и техническая запись останутся проверяемыми.',
      'secureOriginalsWithdrawConfirm': 'ОТОЗВАТЬ',
      'secureOriginalsWithdrawing': 'Отзыв официальной копии...',
      'secureOriginalsWithdrawn': 'Официальная копия отозвана.',
      'secureOriginalsWithdrawError': 'Не удалось отозвать официальную копию',
      'secureOriginalsWithdrawPending':
          'Отзыв зарегистрирован. Удаление технического эталона ещё ожидается; повторите попытку с этого экрана.',
      'secureOriginalsView': 'ПОСМОТРЕТЬ ОРИГИНАЛ',
      'secureOriginalsShare': 'ПОДЕЛИТЬСЯ ОРИГИНАЛОМ',
      'secureOriginalsOfficialCopy': 'ПОСМОТРЕТЬ ОФИЦИАЛЬНУЮ КОПИЮ',
      'secureOriginalsViewerTitle': 'Оригинал SIGILLUM',
      'secureOriginalStored':
          'Оригинал и HCVPACK зашифрованы в защищённой области SIGILLUM.',
      'secureOriginalStorageDetail':
          'Оригинал не сохраняется в Photos и не отображается в папке Files. Открывайте и отправляйте его из раздела «Защищённые оригиналы».',
      'secureOriginalsOpen': 'ОТКРЫТЬ ЗАЩИЩЁННЫЕ ОРИГИНАЛЫ',
      'secureOriginalsHomeSubtitle':
          'Открывайте, сохраняйте или отправляйте сертифицированные оригиналы.',
      'verifiedOriginalsTitle': 'ЭТАЛОН SIGILLUM',
      'verifiedOriginalsSubtitle':
          'Найдите оригинальный эталон, зарегистрированный до распространения.',
      'verifiedOriginalsAction': 'НАЙТИ ЭТАЛОН SIGILLUM',
      'voPageTitle': 'Оригинальный эталон SIGILLUM',
      'voIntro':
          'Введите HCV-ID, чтобы найти оригинальный эталон, зарегистрированный SIGILLUM до распространения контента.',
      'voFindId': 'НАЙТИ ЭТАЛОН',
      'voSelectProtected': 'ВЫБРАТЬ ИЗ ЗАЩИЩЁННЫХ ОРИГИНАЛОВ',
      'voSelectFile': 'ВЫБРАТЬ ВНЕШНИЙ ФАЙЛ',
      'voProtectedPickError': 'Не удалось открыть защищённые оригиналы.',
      'voInvalidId': 'Недействительный HCV-ID.',
      'voRegistryError':
          'Registry недоступен или вернул некорректный ответ. Результат проверки отсутствует.',
      'voCodeWarning':
          'Наличие кода не доказывает целостность файла из социальной сети: HCV-ID можно скопировать.',
      'voVerifyCodeCertificate': 'ПРОВЕРИТЬ СЕРТИФИКАТ',
      'voAvailable':
          'Оригинальный эталон доступен. Это контент, зарегистрированный SIGILLUM до выдачи наружу.',
      'voWatch': 'ОТКРЫТЬ ОРИГИНАЛЬНЫЙ ЭТАЛОН',
      'voLinkGated':
          'Оригинальный эталон не публикуется по постоянной общедоступной ссылке. Проверка сертификата остаётся бесплатной; эталон открывается внутри SIGILLUM в соответствии с условиями доступа.',
      'voNotAvailable':
          'Оригинальный эталон недоступен. HCV-сертификат всё равно можно проверить.',
      'voSubscriptionRequired':
          'Проверка сертификата остаётся бесплатной. Для просмотра официальной копии через SIGILLUM требуется активная подписка.',
      'voAuthRequired':
          'Войдите в аккаунт SIGILLUM с активной подпиской, чтобы посмотреть официальную копию.',
      'voOpenError': 'Не удалось открыть официальную копию.',
      'voFilePickError': 'Не удалось открыть выбранный файл.',
    },
  };
}
