class VerificationUiCopy {
  const VerificationUiCopy._();

  static String t(String languageCode, String key) {
    final code = _copy.containsKey(languageCode) ? languageCode : 'en';
    return _copy[code]?[key] ?? _copy['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _copy = {
    'it': {
      'verifyTitle': 'Verifica contenuto',
      'verifyText': 'VERIFICA TESTO',
      'verifyPhoto': 'VERIFICA FOTO',
      'verifyVideo': 'VERIFICA VIDEO',
      'fastCheck': 'Controllo rapido SIGILLUM...',
      'notCertified': 'Contenuto non certificato SIGILLUM',
      'idDetected': 'HCV-ID rilevato. Verifica certificato in corso...',
      'fastHelp': 'Cerco subito il marchio HCV e il codice. Se non sono presenti, il controllo si ferma qui.',
      'noId': 'Non è stato rilevato un HCV-ID valido nel contenuto selezionato.',
      'backVerify': 'TORNA ALLA VERIFICA',
      'provenance': 'Provenienza',
      'provenanceHint': 'Chi lo certifica',
      'integrity': 'Integrità',
      'integrityHint': 'Originale o modificato',
      'scene': 'Scena',
      'sceneHint': 'Realtà o schermo',
      'derivation': 'Derivazione',
      'derivationHint': 'Originale o copia',
      'verified': 'Verificata',
      'originalIntact': 'Originale integro',
      'compatibleDerivative': 'Contenuto certificato compatibile',
      'realityDetected': 'Realtà rilevata',
      'noScreenEvidence': 'Nessun indizio display',
      'sceneUncertain': 'Non conclusiva',
      'screenRisk': 'Possibile schermo',
      'derivationNotNeeded': 'Non necessaria',
      'compatible': 'Non determinabile',
      'notVerified': 'Non verificata',
      'notDetermined': 'Non determinata',
      'notAnalyzed': 'Non analizzata',
      'provenanceOkDetail': 'Certificato e identità tecnica collegati al contenuto.',
      'originalDetail': 'Hash SHA-256 identico all originale certificato.',
      'derivedDetail': 'Hash diverso dall’originale certificato, ma HCV-ID e fingerprint restano compatibili.',
      'realityDetail': 'Geometria a più profondità rilevata; nessuna evidenza confermata di schermo.',
      'noScreenDetail': 'Nessun indizio tecnico sufficiente di ripresa da schermo.',
      'uncertainDetail': 'Segnali ambigui: non bastano per stabilire realtà o schermo.',
      'screenDetail': 'Segnali tecnici coerenti con una possibile ripresa da schermo.',
      'originalDerivationDetail': 'Il file corrisponde esattamente all originale.',
      'derivedDerivationDetail': 'Versione derivata compatibile; la verifica non distingue da sola tra sottotitoli, ricompressione o altre modifiche.',
      'forensicOk': 'Originale certificato verificato',
      'forensicOkDetail': 'Il file è identico all originale registrato da SIGILLUM.',
      'socialOk': 'Contenuto certificato compatibile verificato',
      'socialOkDetail': 'Il file è diverso dall’originale certificato, ma resta collegato al certificato SIGILLUM tramite HCV-ID e fingerprint.',
      'technicalDetails': 'Dettagli tecnici',
      'selectOriginal': 'SELEZIONA MEDIA ORIGINALE',
      'verifyRegistry': 'VERIFICA DAL REGISTRY',
      'verifying': 'VERIFICA...',
      'registryUnavailable': 'Registry temporaneamente non raggiungibile.',
      'registryNotFound': 'Certificato non presente nel Registry.',
      'verificationIncomplete': 'Verifica non completata.',
      'registryHelper': 'Il certificato viene recuperato automaticamente dal Registry HCV. Seleziona il file che vuoi verificare.',
      'routerTitle': 'Verifica contenuto',
      'packAnalyzing': 'Analisi HCVPACK...',
      'packInvalid': 'HCVPACK non valido',
      'packIncomplete': 'HCVPACK incompleto',
      'fileNotFound': 'File non trovato',
      'verificationComplete': 'Verifica completata',
    },
    'en': {
      'verifyTitle': 'Verify content',
      'verifyText': 'VERIFY TEXT',
      'verifyPhoto': 'VERIFY PHOTO',
      'verifyVideo': 'VERIFY VIDEO',
      'fastCheck': 'Quick SIGILLUM check...',
      'notCertified': 'Content not certified by SIGILLUM',
      'idDetected': 'HCV-ID detected. Verifying certificate...',
      'fastHelp': 'SIGILLUM checks immediately for the HCV mark and code. If they are absent, verification stops here.',
      'noId': 'No valid HCV-ID was detected in the selected content.',
      'backVerify': 'BACK TO VERIFICATION',
      'provenance': 'Provenance',
      'provenanceHint': 'Who certified it',
      'integrity': 'Integrity',
      'integrityHint': 'Original or changed',
      'scene': 'Scene',
      'sceneHint': 'Reality or screen',
      'derivation': 'Derivation',
      'derivationHint': 'Original or copy',
      'verified': 'Verified',
      'originalIntact': 'Original intact',
      'compatibleDerivative': 'Certified compatible content',
      'realityDetected': 'Reality detected',
      'noScreenEvidence': 'No display evidence',
      'sceneUncertain': 'Inconclusive',
      'screenRisk': 'Possible screen',
      'derivationNotNeeded': 'Not needed',
      'compatible': 'No determinable',
      'notVerified': 'Not verified',
      'notDetermined': 'Not determined',
      'notAnalyzed': 'Not analyzed',
      'provenanceOkDetail': 'Certificate and technical identity are linked to the content.',
      'originalDetail': 'SHA-256 hash matches the certified original.',
      'derivedDetail': 'The hash differs from the certified original, but HCV-ID and fingerprint remain compatible.',
      'realityDetail': 'Multi-depth geometry detected; no confirmed screen evidence.',
      'noScreenDetail': 'No sufficient technical evidence of screen replay.',
      'uncertainDetail': 'Signals are ambiguous and do not establish reality or screen.',
      'screenDetail': 'Technical signals are consistent with a possible screen replay.',
      'originalDerivationDetail': 'The file exactly matches the original.',
      'derivedDerivationDetail': 'Compatible derived version; verification alone does not distinguish subtitles, recompression, or other edits.',
      'forensicOk': 'Certified original verified',
      'forensicOkDetail': 'The file is identical to the original registered by SIGILLUM.',
      'socialOk': 'Certified compatible content verified',
      'socialOkDetail': 'The file differs from the certified original but remains linked to the SIGILLUM certificate through its HCV-ID and fingerprint.',
      'technicalDetails': 'Technical details',
      'selectOriginal': 'SELECT ORIGINAL MEDIA',
      'verifyRegistry': 'VERIFY FROM REGISTRY',
      'verifying': 'VERIFYING...',
      'registryUnavailable': 'Registry is temporarily unavailable.',
      'registryNotFound': 'Certificate not found in the Registry.',
      'verificationIncomplete': 'Verification was not completed.',
      'registryHelper': 'The certificate is retrieved automatically from the HCV Registry. Select the file you want to verify.',
      'routerTitle': 'Verify content',
      'packAnalyzing': 'Analyzing HCVPACK...',
      'packInvalid': 'Invalid HCVPACK',
      'packIncomplete': 'Incomplete HCVPACK',
      'fileNotFound': 'File not found',
      'verificationComplete': 'Verification complete',
    },
    'es': {
      'verifyTitle': 'Verificar contenido',
      'verifyText': 'VERIFICAR TEXTO',
      'verifyPhoto': 'VERIFICAR FOTO',
      'verifyVideo': 'VERIFICAR VIDEO',
      'fastCheck': 'Comprobación rápida SIGILLUM...',
      'notCertified': 'Contenido no certificado por SIGILLUM',
      'idDetected': 'HCV-ID detectado. Verificando certificado...',
      'fastHelp': 'SIGILLUM busca inmediatamente la marca HCV y el código. Si no están presentes, la verificación termina aquí.',
      'noId': 'No se detectó un HCV-ID válido en el contenido seleccionado.',
      'backVerify': 'VOLVER A VERIFICAR',
      'provenance': 'Procedencia',
      'provenanceHint': 'Quién lo certifica',
      'integrity': 'Integridad',
      'integrityHint': 'Original o modificado',
      'scene': 'Escena',
      'sceneHint': 'Realidad o pantalla',
      'derivation': 'Derivación',
      'derivationHint': 'Original o copia',
      'verified': 'Verificada',
      'originalIntact': 'Original íntegro',
      'compatibleDerivative': 'Contenido certificado compatible',
      'realityDetected': 'Realidad detectada',
      'noScreenEvidence': 'Sin indicios de pantalla',
      'sceneUncertain': 'No concluyente',
      'screenRisk': 'Posible pantalla',
      'derivationNotNeeded': 'No necesaria',
      'compatible': 'No determinable',
      'notVerified': 'No verificada',
      'notDetermined': 'No determinada',
      'notAnalyzed': 'No analizada',
      'provenanceOkDetail': 'El certificado y la identidad técnica están vinculados al contenido.',
      'originalDetail': 'El hash SHA-256 coincide con el original certificado.',
      'derivedDetail': 'El hash difiere del original certificado, pero el HCV-ID y la huella siguen siendo compatibles.',
      'realityDetail': 'Se detectó geometría de múltiples profundidades; no hay evidencia confirmada de pantalla.',
      'noScreenDetail': 'No hay evidencia técnica suficiente de reproducción desde pantalla.',
      'uncertainDetail': 'Las señales son ambiguas y no permiten determinar realidad o pantalla.',
      'screenDetail': 'Las señales técnicas son compatibles con una posible reproducción desde pantalla.',
      'originalDerivationDetail': 'El archivo coincide exactamente con el original.',
      'derivedDerivationDetail': 'Versión derivada compatible; la verificación por sí sola no distingue entre subtítulos, recompresión u otras modificaciones.',
      'forensicOk': 'Original certificado verificado',
      'forensicOkDetail': 'El archivo es idéntico al original registrado por SIGILLUM.',
      'socialOk': 'Contenido certificado compatible verificado',
      'socialOkDetail': 'El archivo difiere del original certificado, pero sigue vinculado al certificado SIGILLUM mediante el HCV-ID y la huella.',
      'technicalDetails': 'Detalles técnicos',
      'selectOriginal': 'SELECCIONAR MEDIA ORIGINAL',
      'verifyRegistry': 'VERIFICAR EN REGISTRY',
      'verifying': 'VERIFICANDO...',
      'registryUnavailable': 'Registry no está disponible temporalmente.',
      'registryNotFound': 'Certificado no encontrado en Registry.',
      'verificationIncomplete': 'No se completó la verificación.',
      'registryHelper': 'El certificado se recupera automáticamente del Registry HCV. Selecciona el archivo que quieres verificar.',
      'routerTitle': 'Verificar contenido',
      'packAnalyzing': 'Analizando HCVPACK...',
      'packInvalid': 'HCVPACK no válido',
      'packIncomplete': 'HCVPACK incompleto',
      'fileNotFound': 'Archivo no encontrado',
      'verificationComplete': 'Verificación completada',
    },
    'ru': {
      'verifyTitle': 'Проверка контента',
      'verifyText': 'ПРОВЕРИТЬ ТЕКСТ',
      'verifyPhoto': 'ПРОВЕРИТЬ ФОТО',
      'verifyVideo': 'ПРОВЕРИТЬ ВИДЕО',
      'fastCheck': 'Быстрая проверка SIGILLUM...',
      'notCertified': 'Контент не сертифицирован SIGILLUM',
      'idDetected': 'HCV-ID найден. Проверяется сертификат...',
      'fastHelp': 'SIGILLUM сразу ищет метку HCV и код. Если их нет, проверка завершается.',
      'noId': 'В выбранном контенте не найден действительный HCV-ID.',
      'backVerify': 'НАЗАД К ПРОВЕРКЕ',
      'provenance': 'Происхождение',
      'provenanceHint': 'Кто сертифицировал',
      'integrity': 'Целостность',
      'integrityHint': 'Оригинал или изменён',
      'scene': 'Сцена',
      'sceneHint': 'Реальность или экран',
      'derivation': 'Производность',
      'derivationHint': 'Оригинал или копия',
      'verified': 'Подтверждено',
      'originalIntact': 'Оригинал цел',
      'compatibleDerivative': 'Совместимый сертифицированный контент',
      'realityDetected': 'Реальность обнаружена',
      'noScreenEvidence': 'Признаков экрана нет',
      'sceneUncertain': 'Неоднозначно',
      'screenRisk': 'Возможен экран',
      'derivationNotNeeded': 'Не требуется',
      'compatible': 'Причина не определена',
      'notVerified': 'Не подтверждено',
      'notDetermined': 'Не определено',
      'notAnalyzed': 'Не анализировалось',
      'provenanceOkDetail': 'Сертификат и техническая личность связаны с контентом.',
      'originalDetail': 'SHA-256 совпадает с сертифицированным оригиналом.',
      'derivedDetail': 'Хэш отличается от сертифицированного оригинала, но HCV-ID и отпечаток остаются совместимыми.',
      'realityDetail': 'Обнаружена многоглубинная геометрия; подтверждённых признаков экрана нет.',
      'noScreenDetail': 'Недостаточно технических признаков съёмки с экрана.',
      'uncertainDetail': 'Сигналы неоднозначны и не позволяют определить реальность или экран.',
      'screenDetail': 'Технические сигналы совместимы с возможной съёмкой с экрана.',
      'originalDerivationDetail': 'Файл точно соответствует оригиналу.',
      'derivedDerivationDetail': 'Совместимая производная версия; сама проверка не различает субтитры, перекодирование и другие изменения.',
      'forensicOk': 'Сертифицированный оригинал подтверждён',
      'forensicOkDetail': 'Файл идентичен оригиналу, зарегистрированному SIGILLUM.',
      'socialOk': 'Совместимый сертифицированный контент подтверждён',
      'socialOkDetail': 'Файл отличается от сертифицированного оригинала, но остаётся связан с сертификатом SIGILLUM через HCV-ID и отпечаток.',
      'technicalDetails': 'Технические детали',
      'selectOriginal': 'ВЫБРАТЬ ОРИГИНАЛЬНЫЙ ФАЙЛ',
      'verifyRegistry': 'ПРОВЕРИТЬ В REGISTRY',
      'verifying': 'ПРОВЕРКА...',
      'registryUnavailable': 'Registry временно недоступен.',
      'registryNotFound': 'Сертификат не найден в Registry.',
      'verificationIncomplete': 'Проверка не завершена.',
      'registryHelper': 'Сертификат автоматически загружается из Registry HCV. Выберите файл, который хотите проверить.',
      'routerTitle': 'Проверка контента',
      'packAnalyzing': 'Анализ HCVPACK...',
      'packInvalid': 'Недействительный HCVPACK',
      'packIncomplete': 'Неполный HCVPACK',
      'fileNotFound': 'Файл не найден',
      'verificationComplete': 'Проверка завершена',
    },
  };
}
