class VerificationUiCopy {
  const VerificationUiCopy._();

  static String t(String languageCode, String key) {
    final code = _copy.containsKey(languageCode) ? languageCode : 'en';
    return _copy[code]?[key] ?? _copy['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _copy = {
    'it': {
      'verifyTitle': 'Verifica contenuto',
      'verifyText': 'VERIFICA TESTO',
      'verifyPhoto': 'VERIFICA FOTO',
      'verifyVideo': 'VERIFICA VIDEO',
      'fastCheck': 'Controllo rapido SIGILLUM...',
      'notCertified': 'Contenuto non certificato SIGILLUM',
      'idDetected': 'HCV-ID rilevato. Verifica certificato in corso...',
      'fastHelp': 'Cerco subito il marchio HCV e il codice. Se non sono presenti, il controllo si ferma qui.',
      'noId': 'Non è stato rilevato un HCV-ID valido nel contenuto selezionato.',
      'backVerify': 'TORNA ALLA VERIFICA',
      'provenance': 'Provenienza',
      'provenanceHint': 'Chi lo certifica',
      'integrity': 'Integrità',
      'integrityHint': 'Originale o modificato',
      'scene': 'Scena',
      'sceneHint': 'Scena fisica o display',
      'originalScene': 'Scena dell’originale',
      'originalSceneHint': 'Valutazione firmata alla cattura',
      'originalSceneCopyQualifier': 'Questa valutazione appartiene all’originale certificato e non viene ricalcolata sulla copia social.',
      'derivation': 'Derivazione',
      'derivationHint': 'Originale o copia',
      'verified': 'Verificata',
      'originalIntact': 'Originale integro',
      'compatibleDerivative': 'Copia compatibile con l’origine',
      'realityDetected': 'Indizi di scena fisica',
      'noScreenEvidence': 'Nessun indizio display',
      'sceneUncertain': 'Non conclusiva',
      'screenRisk': 'Possibile ripresa da schermo',
      'derivationNotNeeded': 'Non necessaria',
      'compatible': 'Non determinabile',
      'notVerified': 'Non verificata',
      'notDetermined': 'Non determinata',
      'notAnalyzed': 'Non analizzata',
      'provenanceOkDetail': 'Certificato e identità tecnica collegati al contenuto.',
      'originalDetail': 'Hash SHA-256 identico all originale certificato.',
      'derivedDetail': 'Hash diverso dall’originale certificato, ma i controlli di compatibilità previsti per questo media sono superati. Nei video moderni fingerprint visivo e audio sono verificati separatamente.',
      'realityDetail': 'Geometria a più profondità coerente con una scena fisica; nessuna evidenza confermata di display.',
      'noScreenDetail': 'Nessun indizio tecnico sufficiente di ripresa da schermo.',
      'uncertainDetail': 'Segnali ambigui: i controlli non distinguono in modo conclusivo scena fisica e display.',
      'screenDetail': 'Segnali tecnici coerenti con una possibile ripresa da schermo.',
      'originalDerivationDetail': 'Il file corrisponde esattamente all originale.',
      'derivedDerivationDetail': 'Versione derivata compatibile; la verifica non distingue da sola tra sottotitoli, ricompressione o altre modifiche.',
      'forensicOk': 'ORIGINALE SIGILLUM — IDENTICO',
      'forensicOkDetail': 'Il file è identico byte per byte all’originale certificato da SIGILLUM.',
      'socialOk': 'COPIA COMPATIBILE CON L’ORIGINALE SIGILLUM',
      'socialOkDetail': 'Il file è diverso dall’originale esatto ma supera i controlli di compatibilità previsti. Nei video moderni immagine e audio vengono verificati separatamente.',
      'technicalDetails': 'Dettagli tecnici',
      'selectOriginal': 'SELEZIONA MEDIA ORIGINALE',
      'verifyRegistry': 'VERIFICA DAL REGISTRY',
      'verifying': 'VERIFICA...',
      'registryUnavailable': 'Registry temporaneamente non raggiungibile.',
      'registryNotFound': 'Certificato non presente nel Registry.',
      'verificationIncomplete': 'Verifica non completata.',
      'registryHelper': 'Il certificato viene recuperato automaticamente dal Registry HCV. Seleziona il file che vuoi verificare.',
      'routerTitle': 'Verifica contenuto',
      'packAnalyzing': 'Analisi HCVPACK...',
      'packInvalid': 'HCVPACK non valido',
      'packIncomplete': 'HCVPACK incompleto',
      'fileNotFound': 'File non trovato',
      'packVerifiedResult': 'HCVPACK VERIFICATO',
      'verificationComplete': 'Verifica completata',
    },
    'en': {
      'verifyTitle': 'Verify content',
      'verifyText': 'VERIFY TEXT',
      'verifyPhoto': 'VERIFY PHOTO',
      'verifyVideo': 'VERIFY VIDEO',
      'fastCheck': 'Quick SIGILLUM check...',
      'notCertified': 'Content not certified by SIGILLUM',
      'idDetected': 'HCV-ID detected. Verifying certificate...',
      'fastHelp': 'SIGILLUM checks immediately for the HCV mark and code. If they are absent, verification stops here.',
      'noId': 'No valid HCV-ID was detected in the selected content.',
      'backVerify': 'BACK TO VERIFICATION',
      'provenance': 'Provenance',
      'provenanceHint': 'Who certified it',
      'integrity': 'Integrity',
      'integrityHint': 'Original or changed',
      'scene': 'Scene',
      'sceneHint': 'Physical scene or display',
      'originalScene': 'Original scene',
      'originalSceneHint': 'Signed capture-time assessment',
      'originalSceneCopyQualifier': 'This assessment belongs to the certified original and is not recalculated on the social copy.',
      'derivation': 'Derivation',
      'derivationHint': 'Original or copy',
      'verified': 'Verified',
      'originalIntact': 'Original intact',
      'compatibleDerivative': 'Copy compatible with the origin',
      'realityDetected': 'Physical-scene evidence',
      'noScreenEvidence': 'No display evidence',
      'sceneUncertain': 'Inconclusive',
      'screenRisk': 'Possible screen recapture',
      'derivationNotNeeded': 'Not needed',
      'compatible': 'Cannot be determined',
      'notVerified': 'Not verified',
      'notDetermined': 'Not determined',
      'notAnalyzed': 'Not analyzed',
      'provenanceOkDetail': 'Certificate and technical identity are linked to the content.',
      'originalDetail': 'SHA-256 hash matches the certified original.',
      'derivedDetail': 'The hash differs from the certified original, but the compatibility checks required for this media pass. Modern videos verify visual and audio fingerprints separately.',
      'realityDetail': 'Multi-depth geometry is consistent with a physical scene; no confirmed display evidence.',
      'noScreenDetail': 'No sufficient technical evidence of screen replay.',
      'uncertainDetail': 'Signals are ambiguous: the checks do not conclusively distinguish a physical scene from a display.',
      'screenDetail': 'Technical signals are consistent with a possible screen replay.',
      'originalDerivationDetail': 'The file exactly matches the original.',
      'derivedDerivationDetail': 'Compatible derived version; verification alone does not distinguish subtitles, recompression, or other edits.',
      'forensicOk': 'SIGILLUM ORIGINAL — IDENTICAL',
      'forensicOkDetail': 'The file is byte-for-byte identical to the original certified by SIGILLUM.',
      'socialOk': 'COPY COMPATIBLE WITH THE SIGILLUM ORIGINAL',
      'socialOkDetail': 'The file differs from the exact original but passes the applicable compatibility checks. Modern videos verify image and audio separately.',
      'technicalDetails': 'Technical details',
      'selectOriginal': 'SELECT ORIGINAL MEDIA',
      'verifyRegistry': 'VERIFY FROM REGISTRY',
      'verifying': 'VERIFYING...',
      'registryUnavailable': 'Registry is temporarily unavailable.',
      'registryNotFound': 'Certificate not found in the Registry.',
      'verificationIncomplete': 'Verification was not completed.',
      'registryHelper': 'The certificate is retrieved automatically from the HCV Registry. Select the file you want to verify.',
      'routerTitle': 'Verify content',
      'packAnalyzing': 'Analyzing HCVPACK...',
      'packInvalid': 'Invalid HCVPACK',
      'packIncomplete': 'Incomplete HCVPACK',
      'fileNotFound': 'File not found',
      'packVerifiedResult': 'HCVPACK VERIFIED',
      'verificationComplete': 'Verification complete',
    },
    'es': {
      'verifyTitle': 'Verificar contenido',
      'verifyText': 'VERIFICAR TEXTO',
      'verifyPhoto': 'VERIFICAR FOTO',
      'verifyVideo': 'VERIFICAR VIDEO',
      'fastCheck': 'Comprobación rápida SIGILLUM...',
      'notCertified': 'Contenido no certificado por SIGILLUM',
      'idDetected': 'HCV-ID detectado. Verificando certificado...',
      'fastHelp': 'SIGILLUM busca inmediatamente la marca HCV y el código. Si no están presentes, la verificación termina aquí.',
      'noId': 'No se detectó un HCV-ID válido en el contenido seleccionado.',
      'backVerify': 'VOLVER A VERIFICAR',
      'provenance': 'Procedencia',
      'provenanceHint': 'Quién lo certifica',
      'integrity': 'Integridad',
      'integrityHint': 'Original o modificado',
      'scene': 'Escena',
      'sceneHint': 'Escena física o pantalla',
      'originalScene': 'Escena del original',
      'originalSceneHint': 'Evaluación firmada durante la captura',
      'originalSceneCopyQualifier': 'Esta evaluación pertenece al original certificado y no se vuelve a calcular sobre la copia social.',
      'derivation': 'Derivación',
      'derivationHint': 'Original o copia',
      'verified': 'Verificada',
      'originalIntact': 'Original íntegro',
      'compatibleDerivative': 'Copia compatible con el origen',
      'realityDetected': 'Indicios de escena física',
      'noScreenEvidence': 'Sin indicios de pantalla',
      'sceneUncertain': 'No concluyente',
      'screenRisk': 'Posible recaptura de pantalla',
      'derivationNotNeeded': 'No necesaria',
      'compatible': 'Cannot be determined',
      'notVerified': 'No verificada',
      'notDetermined': 'No determinada',
      'notAnalyzed': 'No analizada',
      'provenanceOkDetail': 'El certificado y la identidad técnica están vinculados al contenido.',
      'originalDetail': 'El hash SHA-256 coincide con el original certificado.',
      'derivedDetail': 'El hash difiere del original certificado, pero supera los controles de compatibilidad previstos para este media. En vídeos modernos se verifican por separado las huellas visual y de audio.',
      'realityDetail': 'La geometría de múltiples profundidades es coherente con una escena física; no hay evidencia confirmada de pantalla.',
      'noScreenDetail': 'No hay evidencia técnica suficiente de reproducción desde pantalla.',
      'uncertainDetail': 'Las señales son ambiguas: los controles no distinguen de forma concluyente entre escena física y pantalla.',
      'screenDetail': 'Las señales técnicas son compatibles con una posible reproducción desde pantalla.',
      'originalDerivationDetail': 'El archivo coincide exactamente con el original.',
      'derivedDerivationDetail': 'Versión derivada compatible; la verificación por sí sola no distingue entre subtítulos, recompresión u otras modificaciones.',
      'forensicOk': 'ORIGINAL SIGILLUM — IDÉNTICO',
      'forensicOkDetail': 'El archivo es idéntico byte por byte al original certificado por SIGILLUM.',
      'socialOk': 'COPIA COMPATIBLE CON EL ORIGINAL SIGILLUM',
      'socialOkDetail': 'El archivo difiere del original exacto, pero supera los controles de compatibilidad aplicables. En vídeos modernos se verifican por separado imagen y audio.',
      'technicalDetails': 'Detalles técnicos',
      'selectOriginal': 'SELECCIONAR MEDIA ORIGINAL',
      'verifyRegistry': 'VERIFICAR EN REGISTRY',
      'verifying': 'VERIFICANDO...',
      'registryUnavailable': 'Registry no está disponible temporalmente.',
      'registryNotFound': 'Certificado no encontrado en Registry.',
      'verificationIncomplete': 'No se completó la verificación.',
      'registryHelper': 'El certificado se recupera automáticamente del Registry HCV. Selecciona el archivo que quieres verificar.',
      'routerTitle': 'Verificar contenido',
      'packAnalyzing': 'Analizando HCVPACK...',
      'packInvalid': 'HCVPACK no válido',
      'packIncomplete': 'HCVPACK incompleto',
      'fileNotFound': 'Archivo no encontrado',
      'packVerifiedResult': 'HCVPACK VERIFICADO',
      'verificationComplete': 'Verificación completada',
    },
    'ru': {
      'verifyTitle': 'Проверка контента',
      'verifyText': 'ПРОВЕРИТЬ ТЕКСТ',
      'verifyPhoto': 'ПРОВЕРИТЬ ФОТО',
      'verifyVideo': 'ПРОВЕРИТЬ ВИДЕО',
      'fastCheck': 'Быстрая проверка SIGILLUM...',
      'notCertified': 'Контент не сертифицирован SIGILLUM',
      'idDetected': 'HCV-ID найден. Проверяется сертификат...',
      'fastHelp': 'SIGILLUM сразу ищет метку HCV и код. Если их нет, проверка завершается.',
      'noId': 'В выбранном контенте не найден действительный HCV-ID.',
      'backVerify': 'НАЗАД К ПРОВЕРКЕ',
      'provenance': 'Происхождение',
      'provenanceHint': 'Кто сертифицировал',
      'integrity': 'Целостность',
      'integrityHint': 'Оригинал или изменён',
      'scene': 'Сцена',
      'sceneHint': 'Физическая сцена или экран',
      'originalScene': 'Сцена оригинала',
      'originalSceneHint': 'Подписанная оценка при съёмке',
      'originalSceneCopyQualifier': 'Эта оценка относится к сертифицированному оригиналу и не пересчитывается для копии из соцсети.',
      'derivation': 'Производность',
      'derivationHint': 'Оригинал или копия',
      'verified': 'Подтверждено',
      'originalIntact': 'Оригинал цел',
      'compatibleDerivative': 'Копия совместима с происхождением',
      'realityDetected': 'Признаки физической сцены',
      'noScreenEvidence': 'Признаков экрана нет',
      'sceneUncertain': 'Неоднозначно',
      'screenRisk': 'Возможна пересъёмка с экрана',
      'derivationNotNeeded': 'Не требуется',
      'compatible': 'Причина не определена',
      'notVerified': 'Не подтверждено',
      'notDetermined': 'Не определено',
      'notAnalyzed': 'Не анализировалось',
      'provenanceOkDetail': 'Сертификат и техническая личность связаны с контентом.',
      'originalDetail': 'SHA-256 совпадает с сертифицированным оригиналом.',
      'derivedDetail': 'Хэш отличается от сертифицированного оригинала, но файл проходит предусмотренные для этого типа медиа проверки совместимости. В современных видео визуальный и аудиоотпечатки проверяются отдельно.',
      'realityDetail': 'Многоглубинная геометрия соответствует физической сцене; подтверждённых признаков экрана нет.',
      'noScreenDetail': 'Недостаточно технических признаков съёмки с экрана.',
      'uncertainDetail': 'Сигналы неоднозначны: проверки не позволяют однозначно отличить физическую сцену от экрана.',
      'screenDetail': 'Технические сигналы совместимы с возможной съёмкой с экрана.',
      'originalDerivationDetail': 'Файл точно соответствует оригиналу.',
      'derivedDerivationDetail': 'Совместимая производная версия; сама проверка не различает субтитры, перекодирование и другие изменения.',
      'forensicOk': 'ОРИГИНАЛ SIGILLUM — ИДЕНТИЧЕН',
      'forensicOkDetail': 'Файл побайтно идентичен оригиналу, сертифицированному SIGILLUM.',
      'socialOk': 'КОПИЯ СОВМЕСТИМА С ОРИГИНАЛОМ SIGILLUM',
      'socialOkDetail': 'Файл отличается от точного оригинала, но проходит применимые проверки совместимости. В современных видео изображение и аудио проверяются отдельно.',
      'technicalDetails': 'Технические детали',
      'selectOriginal': 'ВЫБРАТЬ ОРИГИНАЛЬНЫЙ ФАЙЛ',
      'verifyRegistry': 'ПРОВЕРИТЬ В REGISTRY',
      'verifying': 'ПРОВЕРКА...',
      'registryUnavailable': 'Registry временно недоступен.',
      'registryNotFound': 'Сертификат не найден в Registry.',
      'verificationIncomplete': 'Проверка не завершена.',
      'registryHelper': 'Сертификат автоматически загружается из Registry HCV. Выберите файл, который хотите проверить.',
      'routerTitle': 'Проверка контента',
      'packAnalyzing': 'Анализ HCVPACK...',
      'packInvalid': 'Недействительный HCVPACK',
      'packIncomplete': 'Неполный HCVPACK',
      'fileNotFound': 'Файл не найден',
      'packVerifiedResult': 'HCVPACK ПОДТВЕРЖДЁН',
      'verificationComplete': 'Проверка завершена',
    },
  };
}
