from pathlib import Path


def replace_contract_text(path: Path, replacements: list[tuple[str, str]], label: str) -> None:
    if not path.exists():
        raise RuntimeError(f'{label}: contract file missing: {path}')
    text = path.read_text(encoding='utf-8')
    for old, new in replacements:
        # The RC2 finalizer is intentionally invoked more than once (pre-pub,
        # post-pub and re-finalization). Always recognize the already-final
        # representation BEFORE matching an old anchor that may be a prefix of
        # the new block. This makes every contract migration idempotent.
        if new in text:
            continue
        if old in text:
            text = text.replace(old, new)
            continue
        raise RuntimeError(f'{label}: stale-contract anchor missing: {old}')
    path.write_text(text, encoding='utf-8')


# Build-time safety for the localized Registry presentation helper generated by
# earlier patchers. This is presentation-only and does not touch certification,
# capture, signing, ML thresholds or evidence generation.
registry_path = Path('lib/registry_verify_page.dart')
registry = registry_path.read_text(encoding='utf-8')
old_claims = "    final claims = cert is Map ? cert['claims'] : null;"
new_claims = "    final claims = cert?['claims'];"
if old_claims in registry:
    registry = registry.replace(old_claims, new_claims, 1)
elif new_claims not in registry:
    raise RuntimeError('Registry nullable claims compile anchor missing')
registry_path.write_text(registry, encoding='utf-8')

# The August 18 visual patch generates a transient contract test during CI.
# Its old contract required an obsolete two-card, IT/EN-only verification hub.
# Normalize that generated test to the current three-action, four-language hub.
generated_test = Path('test/prelaunch_visual_caption_refinement_contract_test.dart')
if generated_test.exists():
    text = generated_test.read_text(encoding='utf-8')
    old_block = """    expect(page, contains('VERIFICA TESTO PUBBLICATO'));
    expect(page, contains('TextSocialVerifyPage('));
    expect(page, contains('Verifica foto, video o documento'));"""
    new_block = """    expect(page, contains("VerificationUiCopy.t(widget.languageCode, key)"));
    expect(page, contains("_v('verifyText')"));
    expect(page, contains("_v('verifyPhoto')"));
    expect(page, contains("_v('verifyVideo')"));"""
    if new_block in text:
        pass
    elif old_block in text:
        text = text.replace(old_block, new_block, 1)
    else:
        raise RuntimeError('Generated verification-hub contract anchor missing')
    generated_test.write_text(text, encoding='utf-8')

# Camera localization deliberately removes user-facing Italian/English literals
# from camera_page.dart and resolves them through CameraUiCopy / ExtendedCopy.
# Several older prelaunch contracts are regenerated before this finalizer and
# still assert those literals in camera_page.dart. Align the CONTRACTS with the
# final localized source; never put the literals back into the Camera runtime.
# This changes test expectations only and does not touch capture, evidence,
# signing, detector/fusion logic, iOS runtime code, or HCV claims.
replace_contract_text(
    Path('test/prelaunch_usability_subtitle_account_contract_test.dart'),
    [
        (
            "    final camera = File('lib/camera_page.dart').readAsStringSync();\n",
            "    final camera = File('lib/camera_page.dart').readAsStringSync();\n"
            "    final copy = File('lib/camera_ui_extended_copy.dart').readAsStringSync();\n",
        ),
        (
            "    expect(camera, contains('SALVA VIDEO SOTTOTITOLATO IN FOTO'));",
            "    expect(camera, contains(\"_c('saveCaptionedPhotos')\"));\n"
            "    expect(copy, contains(\"'saveCaptionedPhotos': 'SALVA VIDEO SOTTOTITOLATO IN FOTO'\"));",
        ),
        (
            "    expect(camera, contains('Video SOTTOTITOLATO salvato in Foto'));",
            "    expect(camera, contains(\"_c('captionedSavedPhotos')\"));\n"
            "    expect(copy, contains(\"'captionedSavedPhotos': 'Video sottotitolato salvato in Foto'\"));",
        ),
        (
            "    expect(camera, contains('File > Sul mio iPhone > Fotocamera Sigillum'));",
            "    expect(camera, contains(\"_c('filesPath')\"));\n"
            "    expect(copy, contains(\"'filesPath': 'File > Sul mio iPhone > Fotocamera Sigillum'\"));",
        ),
    ],
    'subtitle localization contract',
)

# This test is generated by the prelaunch product patch, then refined by the
# visual-caption patch. Its old visible-label assertion must follow the final
# localization key while all sidecar/derived-video isolation assertions remain.
product_contract = Path('test/prelaunch_product_refinement_contract_test.dart')
if product_contract.exists():
    replace_contract_text(
        product_contract,
        [
            (
                "    expect(camera, contains('CREA VIDEO CON SOTTOTITOLI'));",
                "    expect(camera, contains(\"_c('createCaptionedVideo')\"));",
            ),
            (
                "    expect(camera, contains('TRASCRIVI AUDIO / CREA SOTTOTITOLI'));",
                "    expect(camera, contains(\"_c('createCaptionedVideo')\"));",
            ),
        ],
        'generated product localization contract',
    )
else:
    raise RuntimeError('generated product localization contract missing')

# The visual-caption test is also transiently generated. Preserve its semantic
# checks (derived video, native burnSubtitles, unchanged certified original),
# but assert the localized call sites instead of obsolete Italian literals.
replace_contract_text(
    Path('test/prelaunch_visual_caption_refinement_contract_test.dart'),
    [
        (
            "    expect(camera, contains('CONDIVIDI VIDEO SOTTOTITOLATO'));",
            "    expect(camera, contains(\"_c('shareCaptionedVideo')\"));",
        ),
        (
            "    expect(camera, contains('L’originale certificato resta invariato.'));",
            "    expect(camera, contains(\"_c('captionExplanation')\"));",
        ),
    ],
    'generated visual-caption localization contract',
)

# Physical-probe copy moved to CameraUiCopy. Keep checking both Italian and
# English copy, plus the camera's localized call site.
replace_contract_text(
    Path('test/physical_probe_user_instruction_test.dart'),
    [
        (
            "    final source = File('lib/camera_page.dart').readAsStringSync();\n",
            "    final source = File('lib/camera_page.dart').readAsStringSync();\n"
            "    final copy = File('lib/camera_ui_copy.dart').readAsStringSync();\n",
        ),
        (
            "    expect(source, contains('MUOVI LEGGERMENTE IL TELEFONO LATERALMENTE'));",
            "    expect(source, contains(\"_c('physicalProbe')\"));\n"
            "    expect(copy, contains(\"'physicalProbe': 'MUOVI LEGGERMENTE IL TELEFONO LATERALMENTE...'\"));",
        ),
        (
            "    expect(source, contains('MOVE THE PHONE SLIGHTLY SIDEWAYS'));",
            "    expect(copy, contains(\"'physicalProbe': 'MOVE THE PHONE SLIGHTLY SIDEWAYS...'\"));",
        ),
    ],
    'physical-probe localization contract',
)

replace_contract_text(
    Path('test/camera_physical_scene_contract_test.dart'),
    [
        (
            "    expect(source, contains('MUOVI LEGGERMENTE IL TELEFONO LATERALMENTE'));",
            "    expect(source, contains(\"_c('physicalProbe')\"));",
        ),
    ],
    'camera physical-scene localization contract',
)

# The REC-ordering contract should order the semantic localized call site, not
# an Italian rendering that now lives in the catalog.
replace_contract_text(
    Path('test/prelaunch_ui_camera_refinement_contract_test.dart'),
    [
        (
            "    expect(source, contains('PRONTO — PREMI REGISTRA PER INIZIARE'));",
            "    expect(source, contains(\"_c('armedVideoReady')\"));",
        ),
        (
            "    final ready = source.indexOf('PRONTO — PREMI REGISTRA PER INIZIARE');",
            "    final ready = source.indexOf(\"_c('armedVideoReady')\");",
        ),
    ],
    'camera REC localization contract',
)

print('Verification Registry compile safety and localized current UI contracts finalized')
