from pathlib import Path

# Build-time safety for the localized Registry presentation helper generated by
# earlier patchers. This is presentation-only and does not touch certification,
# capture, signing, ML thresholds or evidence generation.
registry_path = Path('lib/registry_verify_page.dart')
registry = registry_path.read_text(encoding='utf-8')
old_claims = "    final claims = cert is Map ? cert['claims'] : null;"
new_claims = "    final claims = cert?['claims'];"
if old_claims in registry:
    registry = registry.replace(old_claims, new_claims, 1)
elif new_claims not in registry:
    raise RuntimeError('Registry nullable claims compile anchor missing')
registry_path.write_text(registry, encoding='utf-8')

# The August 18 visual patch generates a transient contract test during CI.
# Its old contract required an obsolete two-card, IT/EN-only verification hub.
# Normalize that generated test to the current three-action, four-language hub.
generated_test = Path('test/prelaunch_visual_caption_refinement_contract_test.dart')
if generated_test.exists():
    text = generated_test.read_text(encoding='utf-8')
    old_block = """    expect(page, contains('VERIFICA TESTO PUBBLICATO'));
    expect(page, contains('TextSocialVerifyPage('));
    expect(page, contains('Verifica foto, video o documento'));"""
    new_block = """    expect(page, contains("VerificationUiCopy.t(widget.languageCode, key)"));
    expect(page, contains("_v('verifyText')"));
    expect(page, contains("_v('verifyPhoto')"));
    expect(page, contains("_v('verifyVideo')"));"""
    if old_block in text:
        text = text.replace(old_block, new_block, 1)
    elif new_block not in text:
        raise RuntimeError('Generated verification-hub contract anchor missing')
    generated_test.write_text(text, encoding='utf-8')

print('Verification Registry compile safety and current UI contracts finalized')
