from pathlib import Path
import runpy

patch_path = Path("tool/apply_ios_share_handoff_fix.py")
source = patch_path.read_text()

unsafe = "updated, count = re.subn(pattern, replacement, source, count=1, flags=re.S)"
safe = "updated, count = re.subn(pattern, lambda _: replacement, source, count=1, flags=re.S)"

if unsafe in source:
    source = source.replace(unsafe, safe, 1)
elif safe not in source:
    raise RuntimeError("Unable to install safe regex replacement mode")

patch_path.write_text(source)
runpy.run_path(str(patch_path), run_name="__main__")

swift_path = Path("ios/SigillumShareExtension/ShareViewController.swift")
swift = swift_path.read_text()

bad_fragments = [
    '"Contenuto pronto.\nTocca APRI SIGILLUM',
    '"Contenuto salvato.\nTocca di nuovo APRI SIGILLUM',
]
for fragment in bad_fragments:
    if fragment in swift:
        raise RuntimeError(
            "Invalid multiline Swift string generated by the share handoff patch"
        )

required_fragments = [
    '"Contenuto pronto.\\nTocca APRI SIGILLUM per verificare."',
    '"Contenuto salvato.\\nTocca di nuovo APRI SIGILLUM oppure apri SIGILLUM manualmente."',
]
for fragment in required_fragments:
    if fragment not in swift:
        raise RuntimeError(
            f"Expected escaped Swift string not generated: {fragment}"
        )

print("Reliable iOS share handoff patch applied and Swift strings validated")
